import { expect, test } from 'vitest'

import * as treePackage from '@workspace/tree'
import type {
  FileTreeBatchOperation,
  FileTreeBuiltInIconSet,
  FileTreeCompositionOptions,
  FileTreeContextMenuItem,
  FileTreeContextMenuOpenContext,
  FileTreeDirectoryHandle,
  FileTreeDragAndDropConfig,
  FileTreeDropContext,
  FileTreeDropResult,
  FileTreeDropTarget,
  FileTreeFileHandle,
  FileTreeGitStatusPatch,
  FileTreeIconConfig,
  FileTreeIcons,
  FileTreeInitialExpansion,
  FileTreeItemHandle,
  FileTreeMoveOptions,
  FileTreeMutationEvent,
  FileTreeMutationEventForType,
  FileTreeMutationEventType,
  FileTreeMutationHandle,
  FileTreeMutationSemanticEvent,
  FileTreeOptions,
  FileTreePreparedInput,
  FileTreeProps,
  FileTreePublicId,
  FileTreeRemoveOptions,
  FileTreeRenameEvent,
  FileTreeRenamingConfig,
  FileTreeResetOptions,
  FileTreeRowDecoration,
  FileTreeRowDecorationContext,
  FileTreeRowDecorationRenderer,
  FileTreeScrollToPathOptions,
  FileTreeSearchBlurBehavior,
  FileTreeSearchMode,
  FileTreeSearchSessionHandle,
  FileTreeSelectionChangeListener,
  FileTreeSortComparator,
  GitStatus,
  GitStatusEntry,
  RemappedIcon,
  UseFileTreeResult,
} from '@workspace/tree'

type PublicTypeAllowlist = readonly [
  FileTreeProps,
  UseFileTreeResult,
  FileTreeOptions,
  FileTreePreparedInput,
  FileTreePublicId,
  FileTreeDirectoryHandle,
  FileTreeFileHandle,
  FileTreeItemHandle,
  FileTreeDropTarget,
  FileTreeDropContext,
  FileTreeDropResult,
  FileTreeRenameEvent,
  FileTreeRowDecorationContext,
  FileTreeContextMenuItem,
  FileTreeContextMenuOpenContext,
  FileTreeBatchOperation,
  FileTreeCompositionOptions,
  FileTreeDragAndDropConfig,
  FileTreeGitStatusPatch,
  FileTreeMoveOptions,
  FileTreeMutationEvent,
  FileTreeMutationEventForType<'*'>,
  FileTreeMutationSemanticEvent,
  FileTreeMutationEventType,
  FileTreeMutationHandle,
  FileTreeRemoveOptions,
  FileTreeRenamingConfig,
  FileTreeResetOptions,
  FileTreeRowDecoration,
  FileTreeRowDecorationRenderer,
  FileTreeScrollToPathOptions,
  FileTreeSearchBlurBehavior,
  FileTreeSearchMode,
  FileTreeSearchSessionHandle,
  FileTreeSelectionChangeListener,
  FileTreeSortComparator,
  FileTreeInitialExpansion,
  FileTreeIcons,
  FileTreeBuiltInIconSet,
  FileTreeIconConfig,
  RemappedIcon,
  GitStatus,
  GitStatusEntry,
]

type PublicTypesAreNameable = PublicTypeAllowlist extends readonly unknown[] ? true : false

const publicTypesAreNameable: PublicTypesAreNameable = true

test('exports only the reviewed runtime and type API', () => {
  expect(Object.keys(treePackage).toSorted()).toEqual([
    'FileTree',
    'FileTreeModel',
    'getBuiltInFileIconColor',
    'prepareFileTreeInput',
    'preparePresortedFileTreeInput',
    'useFileTree',
  ])
  expect(publicTypesAreNameable).toBe(true)
})
