import { defineEditorMetadata } from './metadata'

export const editorCommandMetadata = {
  undo: defineEditorMetadata({
    id: 'undo',
    undoCategory: 'text-edit',
    title: 'Undo',
    vscodeCommandIds: ['undo'],
  }),
  redo: defineEditorMetadata({
    id: 'redo',
    undoCategory: 'text-edit',
    title: 'Redo',
    vscodeCommandIds: ['redo'],
  }),
  find: defineEditorMetadata({
    id: 'find',
    undoCategory: 'view-only',
    title: 'Find',
    vscodeCommandIds: ['actions.find'],
  }),
  findReplace: defineEditorMetadata({
    id: 'findReplace',
    undoCategory: 'view-only',
    title: 'Find and replace',
    vscodeCommandIds: ['editor.action.startFindReplaceAction'],
  }),
  findNext: defineEditorMetadata({
    id: 'findNext',
    undoCategory: 'view-only',
    title: 'Find next',
    vscodeCommandIds: ['editor.action.nextMatchFindAction'],
  }),
  findPrevious: defineEditorMetadata({
    id: 'findPrevious',
    undoCategory: 'view-only',
    title: 'Find previous',
    vscodeCommandIds: ['editor.action.previousMatchFindAction'],
  }),
  goToDefinition: defineEditorMetadata({
    id: 'goToDefinition',
    undoCategory: 'view-only',
    title: 'Go to definition',
    vscodeCommandIds: ['editor.action.revealDefinition'],
  }),
  'editor.action.goToImplementation': defineEditorMetadata({
    hiddenInPalette: true,
    id: 'editor.action.goToImplementation',
    undoCategory: 'view-only',
    title: 'Go to implementation',
    vscodeCommandIds: ['editor.action.goToImplementation'],
  }),
  'editor.action.goToTypeDefinition': defineEditorMetadata({
    hiddenInPalette: true,
    id: 'editor.action.goToTypeDefinition',
    undoCategory: 'view-only',
    title: 'Go to type definition',
    vscodeCommandIds: ['editor.action.goToTypeDefinition'],
  }),
  'editor.action.peekDefinition': defineEditorMetadata({
    hiddenInPalette: true,
    id: 'editor.action.peekDefinition',
    undoCategory: 'view-only',
    title: 'Peek definition',
    vscodeCommandIds: ['editor.action.peekDefinition'],
  }),
  'editor.action.revealDefinitionAside': defineEditorMetadata({
    hiddenInPalette: true,
    id: 'editor.action.revealDefinitionAside',
    undoCategory: 'view-only',
    title: 'Open definition to the side',
    vscodeCommandIds: ['editor.action.revealDefinitionAside'],
  }),
  'editor.action.showHover': defineEditorMetadata({
    id: 'editor.action.showHover',
    undoCategory: 'view-only',
    title: 'Show hover',
    vscodeCommandIds: ['editor.action.showHover'],
  }),
  'editor.action.goToReferences': defineEditorMetadata({
    id: 'editor.action.goToReferences',
    undoCategory: 'view-only',
    title: 'Find references',
    vscodeCommandIds: ['editor.action.goToReferences'],
  }),
  closeFind: defineEditorMetadata({
    id: 'closeFind',
    undoCategory: 'view-only',
    title: 'Close find',
    vscodeCommandIds: ['closeFindWidget'],
  }),
  toggleFindCaseSensitive: defineEditorMetadata({
    id: 'toggleFindCaseSensitive',
    undoCategory: 'view-only',
    title: 'Toggle case sensitive find',
    vscodeCommandIds: ['toggleFindCaseSensitive'],
  }),
  toggleFindWholeWord: defineEditorMetadata({
    id: 'toggleFindWholeWord',
    undoCategory: 'view-only',
    title: 'Toggle whole word find',
    vscodeCommandIds: ['toggleFindWholeWord'],
  }),
  toggleFindRegex: defineEditorMetadata({
    id: 'toggleFindRegex',
    undoCategory: 'view-only',
    title: 'Toggle regex find',
    vscodeCommandIds: ['toggleFindRegex'],
  }),
  toggleFindInSelection: defineEditorMetadata({
    id: 'toggleFindInSelection',
    undoCategory: 'view-only',
    title: 'Toggle find in selection',
    vscodeCommandIds: ['toggleFindInSelection'],
  }),
  togglePreserveCase: defineEditorMetadata({
    id: 'togglePreserveCase',
    undoCategory: 'view-only',
    title: 'Toggle preserve case',
    vscodeCommandIds: ['togglePreserveCase'],
  }),
  replaceOne: defineEditorMetadata({
    id: 'replaceOne',
    undoCategory: 'text-edit',
    title: 'Replace',
    vscodeCommandIds: ['editor.action.replaceOne'],
  }),
  replaceAll: defineEditorMetadata({
    id: 'replaceAll',
    undoCategory: 'text-edit',
    title: 'Replace all',
    vscodeCommandIds: ['editor.action.replaceAll'],
  }),
  selectAllMatches: defineEditorMetadata({
    id: 'selectAllMatches',
    undoCategory: 'view-only',
    title: 'Select all matches',
    vscodeCommandIds: ['editor.action.selectAllMatches'],
  }),
  selectAll: defineEditorMetadata({
    id: 'selectAll',
    undoCategory: 'view-only',
    title: 'Select all',
    vscodeCommandIds: ['editor.action.selectAll'],
  }),
  addNextOccurrence: defineEditorMetadata({
    id: 'addNextOccurrence',
    undoCategory: 'view-only',
    title: 'Add next occurrence',
    vscodeCommandIds: ['editor.action.addSelectionToNextFindMatch'],
  }),
  clearSecondarySelections: defineEditorMetadata({
    id: 'clearSecondarySelections',
    undoCategory: 'view-only',
    title: 'Clear secondary selections',
    vscodeCommandIds: ['removeSecondaryCursors'],
  }),
  deleteWordLeft: defineEditorMetadata({
    id: 'deleteWordLeft',
    undoCategory: 'text-edit',
    title: 'Delete word left',
    vscodeCommandIds: ['deleteWordLeft'],
  }),
  deleteWordRight: defineEditorMetadata({
    id: 'deleteWordRight',
    undoCategory: 'text-edit',
    title: 'Delete word right',
    vscodeCommandIds: ['deleteWordRight'],
  }),
  'editor.action.deleteLines': defineEditorMetadata({
    id: 'editor.action.deleteLines',
    undoCategory: 'text-edit',
    title: 'Delete line',
    vscodeCommandIds: ['editor.action.deleteLines'],
  }),
  'editor.action.copyLinesUpAction': defineEditorMetadata({
    id: 'editor.action.copyLinesUpAction',
    undoCategory: 'text-edit',
    title: 'Copy line up',
    vscodeCommandIds: ['editor.action.copyLinesUpAction'],
  }),
  'editor.action.copyLinesDownAction': defineEditorMetadata({
    id: 'editor.action.copyLinesDownAction',
    undoCategory: 'text-edit',
    title: 'Copy line down',
    vscodeCommandIds: ['editor.action.copyLinesDownAction'],
  }),
  'editor.action.moveLinesUpAction': defineEditorMetadata({
    id: 'editor.action.moveLinesUpAction',
    undoCategory: 'text-edit',
    title: 'Move line up',
    vscodeCommandIds: ['editor.action.moveLinesUpAction'],
  }),
  'editor.action.moveLinesDownAction': defineEditorMetadata({
    id: 'editor.action.moveLinesDownAction',
    undoCategory: 'text-edit',
    title: 'Move line down',
    vscodeCommandIds: ['editor.action.moveLinesDownAction'],
  }),
  'editor.action.insertLineBefore': defineEditorMetadata({
    id: 'editor.action.insertLineBefore',
    undoCategory: 'text-edit',
    title: 'Insert line above',
    vscodeCommandIds: ['editor.action.insertLineBefore'],
  }),
  'editor.action.insertLineAfter': defineEditorMetadata({
    id: 'editor.action.insertLineAfter',
    undoCategory: 'text-edit',
    title: 'Insert line below',
    vscodeCommandIds: ['editor.action.insertLineAfter'],
  }),
  'editor.action.commentLine': defineEditorMetadata({
    id: 'editor.action.commentLine',
    undoCategory: 'text-edit',
    title: 'Toggle line comment',
    vscodeCommandIds: ['editor.action.commentLine'],
  }),
  'editor.action.blockComment': defineEditorMetadata({
    id: 'editor.action.blockComment',
    undoCategory: 'text-edit',
    title: 'Toggle block comment',
    vscodeCommandIds: ['editor.action.blockComment'],
  }),
  'editor.action.indentLines': defineEditorMetadata({
    id: 'editor.action.indentLines',
    undoCategory: 'text-edit',
    title: 'Indent line',
    vscodeCommandIds: ['editor.action.indentLines'],
  }),
  'editor.action.outdentLines': defineEditorMetadata({
    id: 'editor.action.outdentLines',
    undoCategory: 'text-edit',
    title: 'Outdent line',
    vscodeCommandIds: ['editor.action.outdentLines'],
  }),
  'editor.action.insertCursorAbove': defineEditorMetadata({
    id: 'editor.action.insertCursorAbove',
    undoCategory: 'view-only',
    title: 'Add cursor above',
    vscodeCommandIds: ['editor.action.insertCursorAbove'],
  }),
  'editor.action.insertCursorBelow': defineEditorMetadata({
    id: 'editor.action.insertCursorBelow',
    undoCategory: 'view-only',
    title: 'Add cursor below',
    vscodeCommandIds: ['editor.action.insertCursorBelow'],
  }),
  'editor.action.selectHighlights': defineEditorMetadata({
    id: 'editor.action.selectHighlights',
    undoCategory: 'view-only',
    title: 'Select all occurrences',
    vscodeCommandIds: ['editor.action.selectHighlights'],
  }),
  'editor.action.changeAll': defineEditorMetadata({
    id: 'editor.action.changeAll',
    undoCategory: 'view-only',
    title: 'Change all occurrences',
    vscodeCommandIds: ['editor.action.changeAll'],
  }),
  'editor.action.jumpToBracket': defineEditorMetadata({
    id: 'editor.action.jumpToBracket',
    undoCategory: 'view-only',
    title: 'Go to bracket',
    vscodeCommandIds: ['editor.action.jumpToBracket'],
  }),
  cursorWordPartLeft: defineEditorMetadata({
    id: 'cursorWordPartLeft',
    undoCategory: 'view-only',
    title: 'Cursor word part left',
    vscodeCommandIds: ['cursorWordPartLeft'],
  }),
  cursorWordPartRight: defineEditorMetadata({
    id: 'cursorWordPartRight',
    undoCategory: 'view-only',
    title: 'Cursor word part right',
    vscodeCommandIds: ['cursorWordPartRight'],
  }),
  'editor.action.trimTrailingWhitespace': defineEditorMetadata({
    id: 'editor.action.trimTrailingWhitespace',
    undoCategory: 'text-edit',
    title: 'Trim trailing whitespace',
    vscodeCommandIds: ['editor.action.trimTrailingWhitespace'],
  }),
  'editor.action.sortLinesAscending': defineEditorMetadata({
    id: 'editor.action.sortLinesAscending',
    undoCategory: 'text-edit',
    title: 'Sort lines ascending',
    vscodeCommandIds: ['editor.action.sortLinesAscending'],
  }),
  'editor.action.sortLinesDescending': defineEditorMetadata({
    id: 'editor.action.sortLinesDescending',
    undoCategory: 'text-edit',
    title: 'Sort lines descending',
    vscodeCommandIds: ['editor.action.sortLinesDescending'],
  }),
  'editor.action.joinLines': defineEditorMetadata({
    id: 'editor.action.joinLines',
    undoCategory: 'text-edit',
    title: 'Join lines',
    vscodeCommandIds: ['editor.action.joinLines'],
  }),
  'editor.action.duplicateSelection': defineEditorMetadata({
    id: 'editor.action.duplicateSelection',
    undoCategory: 'text-edit',
    title: 'Duplicate selection',
    vscodeCommandIds: ['editor.action.duplicateSelection'],
  }),
  'editor.action.transformToUppercase': defineEditorMetadata({
    id: 'editor.action.transformToUppercase',
    undoCategory: 'text-edit',
    title: 'Transform to uppercase',
    vscodeCommandIds: ['editor.action.transformToUppercase'],
  }),
  'editor.action.transformToLowercase': defineEditorMetadata({
    id: 'editor.action.transformToLowercase',
    undoCategory: 'text-edit',
    title: 'Transform to lowercase',
    vscodeCommandIds: ['editor.action.transformToLowercase'],
  }),
  'editor.action.transformToTitlecase': defineEditorMetadata({
    id: 'editor.action.transformToTitlecase',
    undoCategory: 'text-edit',
    title: 'Transform to title case',
    vscodeCommandIds: ['editor.action.transformToTitlecase'],
  }),
  'editor.action.rename': defineEditorMetadata({
    id: 'editor.action.rename',
    undoCategory: 'text-edit',
    title: 'Rename symbol',
    vscodeCommandIds: ['editor.action.rename'],
  }),
  'editor.action.formatDocument': defineEditorMetadata({
    id: 'editor.action.formatDocument',
    undoCategory: 'text-edit',
    title: 'Format document',
    vscodeCommandIds: ['editor.action.formatDocument'],
  }),
  'editor.action.toggleWordWrap': defineEditorMetadata({
    id: 'editor.action.toggleWordWrap',
    undoCategory: 'view-only',
    title: 'Toggle word wrap',
    vscodeCommandIds: ['editor.action.toggleWordWrap'],
  }),
  'editor.action.moveSelectionToNextFindMatch': defineEditorMetadata({
    id: 'editor.action.moveSelectionToNextFindMatch',
    undoCategory: 'view-only',
    title: 'Move last selection to next find match',
    vscodeCommandIds: ['editor.action.moveSelectionToNextFindMatch'],
  }),
  deleteBackward: defineEditorMetadata({
    id: 'deleteBackward',
    undoCategory: 'text-edit',
    title: 'Delete backward',
  }),
  deleteForward: defineEditorMetadata({
    id: 'deleteForward',
    undoCategory: 'text-edit',
    title: 'Delete forward',
  }),
  indentSelection: defineEditorMetadata({
    id: 'indentSelection',
    undoCategory: 'text-edit',
    title: 'Indent selection',
    vscodeCommandIds: ['tab'],
  }),
  outdentSelection: defineEditorMetadata({
    id: 'outdentSelection',
    undoCategory: 'text-edit',
    title: 'Outdent selection',
    vscodeCommandIds: ['outdent'],
  }),
  cursorLeft: defineEditorMetadata({
    id: 'cursorLeft',
    undoCategory: 'view-only',
    title: 'Move cursor left',
    vscodeCommandIds: ['cursorLeft'],
  }),
  cursorRight: defineEditorMetadata({
    id: 'cursorRight',
    undoCategory: 'view-only',
    title: 'Move cursor right',
    vscodeCommandIds: ['cursorRight'],
  }),
  cursorUp: defineEditorMetadata({
    id: 'cursorUp',
    undoCategory: 'view-only',
    title: 'Move cursor up',
    vscodeCommandIds: ['cursorUp'],
  }),
  cursorDown: defineEditorMetadata({
    id: 'cursorDown',
    undoCategory: 'view-only',
    title: 'Move cursor down',
    vscodeCommandIds: ['cursorDown'],
  }),
  selectLeft: defineEditorMetadata({
    id: 'selectLeft',
    undoCategory: 'view-only',
    title: 'Select left',
    vscodeCommandIds: ['cursorLeftSelect'],
  }),
  selectRight: defineEditorMetadata({
    id: 'selectRight',
    undoCategory: 'view-only',
    title: 'Select right',
    vscodeCommandIds: ['cursorRightSelect'],
  }),
  selectUp: defineEditorMetadata({
    id: 'selectUp',
    undoCategory: 'view-only',
    title: 'Select up',
    vscodeCommandIds: ['cursorUpSelect'],
  }),
  selectDown: defineEditorMetadata({
    id: 'selectDown',
    undoCategory: 'view-only',
    title: 'Select down',
    vscodeCommandIds: ['cursorDownSelect'],
  }),
  cursorWordLeft: defineEditorMetadata({
    id: 'cursorWordLeft',
    undoCategory: 'view-only',
    title: 'Move cursor word left',
    vscodeCommandIds: ['cursorWordLeft'],
  }),
  cursorWordRight: defineEditorMetadata({
    id: 'cursorWordRight',
    undoCategory: 'view-only',
    title: 'Move cursor word right',
    vscodeCommandIds: ['cursorWordRight', 'cursorWordEndRight'],
  }),
  selectWordLeft: defineEditorMetadata({
    id: 'selectWordLeft',
    undoCategory: 'view-only',
    title: 'Select word left',
    vscodeCommandIds: ['cursorWordLeftSelect'],
  }),
  selectWordRight: defineEditorMetadata({
    id: 'selectWordRight',
    undoCategory: 'view-only',
    title: 'Select word right',
    vscodeCommandIds: ['cursorWordRightSelect', 'cursorWordEndRightSelect'],
  }),
  cursorLineStart: defineEditorMetadata({
    id: 'cursorLineStart',
    undoCategory: 'view-only',
    title: 'Move cursor to line start',
    vscodeCommandIds: ['cursorHome', 'cursorLineStart'],
  }),
  cursorLineEnd: defineEditorMetadata({
    id: 'cursorLineEnd',
    undoCategory: 'view-only',
    title: 'Move cursor to line end',
    vscodeCommandIds: ['cursorEnd', 'cursorLineEnd'],
  }),
  selectLineStart: defineEditorMetadata({
    id: 'selectLineStart',
    undoCategory: 'view-only',
    title: 'Select to line start',
    vscodeCommandIds: ['cursorHomeSelect', 'cursorLineStartSelect'],
  }),
  selectLineEnd: defineEditorMetadata({
    id: 'selectLineEnd',
    undoCategory: 'view-only',
    title: 'Select to line end',
    vscodeCommandIds: ['cursorEndSelect', 'cursorLineEndSelect'],
  }),
  cursorPageUp: defineEditorMetadata({
    id: 'cursorPageUp',
    undoCategory: 'view-only',
    title: 'Move cursor page up',
    vscodeCommandIds: ['cursorPageUp'],
  }),
  cursorPageDown: defineEditorMetadata({
    id: 'cursorPageDown',
    undoCategory: 'view-only',
    title: 'Move cursor page down',
    vscodeCommandIds: ['cursorPageDown'],
  }),
  selectPageUp: defineEditorMetadata({
    id: 'selectPageUp',
    undoCategory: 'view-only',
    title: 'Select page up',
    vscodeCommandIds: ['cursorPageUpSelect'],
  }),
  selectPageDown: defineEditorMetadata({
    id: 'selectPageDown',
    undoCategory: 'view-only',
    title: 'Select page down',
    vscodeCommandIds: ['cursorPageDownSelect'],
  }),
  cursorDocumentStart: defineEditorMetadata({
    id: 'cursorDocumentStart',
    undoCategory: 'view-only',
    title: 'Move cursor to document start',
    vscodeCommandIds: ['cursorTop'],
  }),
  cursorDocumentEnd: defineEditorMetadata({
    id: 'cursorDocumentEnd',
    undoCategory: 'view-only',
    title: 'Move cursor to document end',
    vscodeCommandIds: ['cursorBottom'],
  }),
  selectDocumentStart: defineEditorMetadata({
    id: 'selectDocumentStart',
    undoCategory: 'view-only',
    title: 'Select to document start',
    vscodeCommandIds: ['cursorTopSelect'],
  }),
  selectDocumentEnd: defineEditorMetadata({
    id: 'selectDocumentEnd',
    undoCategory: 'view-only',
    title: 'Select to document end',
    vscodeCommandIds: ['cursorBottomSelect'],
  }),
  cursorUndo: defineEditorMetadata({
    id: 'cursorUndo',
    undoCategory: 'view-only',
    title: 'Undo cursor movement',
    vscodeCommandIds: ['cursorUndo'],
  }),
  cursorRedo: defineEditorMetadata({
    id: 'cursorRedo',
    undoCategory: 'view-only',
    title: 'Redo cursor movement',
    vscodeCommandIds: ['cursorRedo'],
  }),
  'editor.action.goToDefinition': defineEditorMetadata({
    id: 'editor.action.goToDefinition',
    undoCategory: 'view-only',
    title: 'Go to definition',
    vscodeCommandIds: ['editor.action.goToDefinition'],
  }),
  'editor.action.marker.next': defineEditorMetadata({
    id: 'editor.action.marker.next',
    undoCategory: 'view-only',
    title: 'Next diagnostic',
    vscodeCommandIds: ['editor.action.marker.next'],
  }),
  'editor.action.marker.prev': defineEditorMetadata({
    id: 'editor.action.marker.prev',
    undoCategory: 'view-only',
    title: 'Previous diagnostic',
    vscodeCommandIds: ['editor.action.marker.prev'],
  }),
  'editor.action.smartSelect.expand': defineEditorMetadata({
    id: 'editor.action.smartSelect.expand',
    undoCategory: 'view-only',
    title: 'Expand selection',
    vscodeCommandIds: ['editor.action.smartSelect.expand'],
  }),
  'editor.action.smartSelect.shrink': defineEditorMetadata({
    id: 'editor.action.smartSelect.shrink',
    undoCategory: 'view-only',
    title: 'Shrink selection',
    vscodeCommandIds: ['editor.action.smartSelect.shrink'],
  }),
  'editor.action.toggleTabFocusMode': defineEditorMetadata({
    id: 'editor.action.toggleTabFocusMode',
    undoCategory: 'view-only',
    title: 'Toggle Tab focus mode',
    vscodeCommandIds: ['editor.action.toggleTabFocusMode'],
  }),
  'editor.action.autoFix': defineEditorMetadata({
    id: 'editor.action.autoFix',
    undoCategory: 'text-edit',
    title: 'Apply auto fix',
    vscodeCommandIds: ['editor.action.autoFix'],
  }),
  'editor.action.inlineSuggest.commit': defineEditorMetadata({
    id: 'editor.action.inlineSuggest.commit',
    undoCategory: 'text-edit',
    title: 'Accept inline suggestion',
    vscodeCommandIds: ['editor.action.inlineSuggest.commit'],
  }),
  'editor.action.inlineSuggest.acceptNextWord': defineEditorMetadata({
    id: 'editor.action.inlineSuggest.acceptNextWord',
    undoCategory: 'text-edit',
    title: 'Accept next word of inline suggestion',
    vscodeCommandIds: ['editor.action.inlineSuggest.acceptNextWord'],
  }),
  'editor.fold': defineEditorMetadata({
    id: 'editor.fold',
    undoCategory: 'view-only',
    title: 'Fold',
    vscodeCommandIds: ['editor.fold'],
  }),
  'editor.unfold': defineEditorMetadata({
    id: 'editor.unfold',
    undoCategory: 'view-only',
    title: 'Unfold',
    vscodeCommandIds: ['editor.unfold'],
  }),
  'editor.foldRecursively': defineEditorMetadata({
    id: 'editor.foldRecursively',
    undoCategory: 'view-only',
    title: 'Fold recursively',
    vscodeCommandIds: ['editor.foldRecursively'],
  }),
  'editor.unfoldRecursively': defineEditorMetadata({
    id: 'editor.unfoldRecursively',
    undoCategory: 'view-only',
    title: 'Unfold recursively',
    vscodeCommandIds: ['editor.unfoldRecursively'],
  }),
  'editor.foldAll': defineEditorMetadata({
    id: 'editor.foldAll',
    undoCategory: 'view-only',
    title: 'Fold all',
    vscodeCommandIds: ['editor.foldAll'],
  }),
  'editor.unfoldAll': defineEditorMetadata({
    id: 'editor.unfoldAll',
    undoCategory: 'view-only',
    title: 'Unfold all',
    vscodeCommandIds: ['editor.unfoldAll'],
  }),
  'editor.createFoldingRangeFromSelection': defineEditorMetadata({
    id: 'editor.createFoldingRangeFromSelection',
    undoCategory: 'view-only',
    title: 'Fold selection',
    vscodeCommandIds: ['editor.createFoldingRangeFromSelection'],
  }),
  'editor.removeManualFoldingRanges': defineEditorMetadata({
    id: 'editor.removeManualFoldingRanges',
    undoCategory: 'view-only',
    title: 'Remove manual folding ranges',
    vscodeCommandIds: ['editor.removeManualFoldingRanges'],
  }),
  deleteWordPartLeft: defineEditorMetadata({
    id: 'deleteWordPartLeft',
    undoCategory: 'text-edit',
    title: 'Delete word part left',
    vscodeCommandIds: ['deleteWordPartLeft'],
  }),
  deleteWordPartRight: defineEditorMetadata({
    id: 'deleteWordPartRight',
    undoCategory: 'text-edit',
    title: 'Delete word part right',
    vscodeCommandIds: ['deleteWordPartRight'],
  }),
  'editor.action.reindentlines': defineEditorMetadata({
    id: 'editor.action.reindentlines',
    undoCategory: 'text-edit',
    title: 'Reindent lines',
    vscodeCommandIds: ['editor.action.reindentlines'],
  }),
  'editor.action.reindentselectedlines': defineEditorMetadata({
    id: 'editor.action.reindentselectedlines',
    undoCategory: 'text-edit',
    title: 'Reindent selected lines',
    vscodeCommandIds: ['editor.action.reindentselectedlines'],
  }),
  cursorWordPartLeftSelect: defineEditorMetadata({
    id: 'cursorWordPartLeftSelect',
    undoCategory: 'view-only',
    title: 'Cursor word part left select',
    vscodeCommandIds: ['cursorWordPartLeftSelect'],
  }),
  cursorWordPartRightSelect: defineEditorMetadata({
    id: 'cursorWordPartRightSelect',
    undoCategory: 'view-only',
    title: 'Cursor word part right select',
    vscodeCommandIds: ['cursorWordPartRightSelect'],
  }),
  cursorColumnSelectLeft: defineEditorMetadata({
    id: 'cursorColumnSelectLeft',
    undoCategory: 'view-only',
    title: 'Cursor column select left',
    vscodeCommandIds: ['cursorColumnSelectLeft'],
  }),
  cursorColumnSelectRight: defineEditorMetadata({
    id: 'cursorColumnSelectRight',
    undoCategory: 'view-only',
    title: 'Cursor column select right',
    vscodeCommandIds: ['cursorColumnSelectRight'],
  }),
  cursorColumnSelectUp: defineEditorMetadata({
    id: 'cursorColumnSelectUp',
    undoCategory: 'view-only',
    title: 'Cursor column select up',
    vscodeCommandIds: ['cursorColumnSelectUp'],
  }),
  cursorColumnSelectDown: defineEditorMetadata({
    id: 'cursorColumnSelectDown',
    undoCategory: 'view-only',
    title: 'Cursor column select down',
    vscodeCommandIds: ['cursorColumnSelectDown'],
  }),
  cursorColumnSelectPageUp: defineEditorMetadata({
    id: 'cursorColumnSelectPageUp',
    undoCategory: 'view-only',
    title: 'Cursor column select page up',
    vscodeCommandIds: ['cursorColumnSelectPageUp'],
  }),
  cursorColumnSelectPageDown: defineEditorMetadata({
    id: 'cursorColumnSelectPageDown',
    undoCategory: 'view-only',
    title: 'Cursor column select page down',
    vscodeCommandIds: ['cursorColumnSelectPageDown'],
  }),
  'editor.foldLevel1': defineEditorMetadata({
    id: 'editor.foldLevel1',
    undoCategory: 'view-only',
    title: 'Fold level1',
    vscodeCommandIds: ['editor.foldLevel1'],
  }),
  'editor.foldLevel2': defineEditorMetadata({
    id: 'editor.foldLevel2',
    undoCategory: 'view-only',
    title: 'Fold level2',
    vscodeCommandIds: ['editor.foldLevel2'],
  }),
  'editor.foldLevel3': defineEditorMetadata({
    id: 'editor.foldLevel3',
    undoCategory: 'view-only',
    title: 'Fold level3',
    vscodeCommandIds: ['editor.foldLevel3'],
  }),
  'editor.foldLevel4': defineEditorMetadata({
    id: 'editor.foldLevel4',
    undoCategory: 'view-only',
    title: 'Fold level4',
    vscodeCommandIds: ['editor.foldLevel4'],
  }),
  'editor.foldLevel5': defineEditorMetadata({
    id: 'editor.foldLevel5',
    undoCategory: 'view-only',
    title: 'Fold level5',
    vscodeCommandIds: ['editor.foldLevel5'],
  }),
  'editor.foldLevel6': defineEditorMetadata({
    id: 'editor.foldLevel6',
    undoCategory: 'view-only',
    title: 'Fold level6',
    vscodeCommandIds: ['editor.foldLevel6'],
  }),
  'editor.foldLevel7': defineEditorMetadata({
    id: 'editor.foldLevel7',
    undoCategory: 'view-only',
    title: 'Fold level7',
    vscodeCommandIds: ['editor.foldLevel7'],
  }),
}
