import { defineMetadata } from './metadata'
import { sessionJumpCommandId, type SessionJumpPosition } from './session-jump'

export const workspaceCommandMetadata = {
  'workspace.undoWorkspaceEdit': defineMetadata({
    category: 'Workspace',
    description: 'Undo the latest atomic multi-file workspace edit.',
    id: 'workspace.undoWorkspaceEdit',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: ['workspaceOpen', 'workspaceEditUndoable'],
    title: 'Undo workspace edit',
  }),
  'workspace.redoWorkspaceEdit': defineMetadata({
    category: 'Workspace',
    description: 'Redo the latest atomic multi-file workspace edit.',
    id: 'workspace.redoWorkspaceEdit',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: ['workspaceOpen', 'workspaceEditRedoable'],
    title: 'Redo workspace edit',
  }),
  'workspace.showQuickAccess': defineMetadata({
    category: 'Workspace',
    description: 'Search workspace files and quick actions.',
    id: 'workspace.showQuickAccess',
    keepsPaletteOpen: true,
    keys: [
      {
        chord: ['Mod+P'],
        preventDefault: true,
        stopPropagation: true,
        vscodeCommandId: 'workbench.action.quickOpen',
      },
      { chord: ['Control+P'], platforms: ['tui'] },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Quick Open',
    vscodeCommandIds: ['workbench.action.quickOpen'],
  }),
  'workspace.showCommandPalette': defineMetadata({
    category: 'Workspace',
    description: 'Search and run workspace or editor commands.',
    hiddenInPalette: true,
    id: 'workspace.showCommandPalette',
    keepsPaletteOpen: true,
    keys: [
      {
        chord: ['Mod+Shift+P'],
        preventDefault: true,
        stopPropagation: true,
        vscodeCommandId: 'workbench.action.showCommands',
      },
      {
        chord: ['F1'],
        preventDefault: true,
        stopPropagation: true,
        vscodeCommandId: 'workbench.action.showCommands',
      },
      { chord: ['F1'], platforms: ['tui'] },
      { chord: ['Control+K', 'P'], platforms: ['tui'] },
      { chord: ['Control+Shift+P'], platforms: ['tui'], terminalProtocol: 'kitty' },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Show command palette',
    vscodeCommandIds: ['workbench.action.showCommands'],
  }),
  'workspace.showSettings': defineMetadata({
    category: 'Workspace',
    description: 'Open providers, models, and keybindings.',
    id: 'workspace.showSettings',
    keys: [
      {
        chord: ['Mod+,'],
        preventDefault: true,
        stopPropagation: true,
        vscodeCommandId: 'workbench.action.openSettings',
      },
      { chord: ['Mod+K', 'Mod+S'], vscodeCommandId: 'workbench.action.openGlobalKeybindings' },
      { chord: ['Control+K', 'S'], platforms: ['tui'] },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Settings',
    vscodeCommandIds: ['workbench.action.openSettings'],
  }),
  'workspace.openFilePicker': defineMetadata({
    category: 'Workspace',
    description: 'Open the workspace file picker.',
    id: 'workspace.openFilePicker',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Open file picker',
    vscodeCommandIds: ['workbench.action.quickOpen'],
  }),
  'workspace.openSearchEditor': defineMetadata({
    category: 'Workspace',
    description: 'Open workspace search results in an editor tab.',
    id: 'workspace.openSearchEditor',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Open Search Editor',
    vscodeCommandIds: ['search.action.openNewEditor'],
  }),
  'workspace.quickOpenPreviousEditor': defineMetadata({
    category: 'Workspace',
    description: 'Switch to the previously active editor.',
    id: 'workspace.quickOpenPreviousEditor',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Quick open previous editor',
    vscodeCommandIds: ['workbench.action.quickOpenPreviousEditor'],
  }),
  'workspace.quickOpenView': defineMetadata({
    keys: [{ chord: ['Control+K', 'V'], platforms: ['tui'] }],
    category: 'Workspace',
    description: 'Search and focus workspace views.',
    id: 'workspace.quickOpenView',
    keepsPaletteOpen: true,
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Open view',
    vscodeCommandIds: ['workbench.action.quickOpenView'],
  }),
  'workspace.gotoSymbol': defineMetadata({
    category: 'Workspace',
    description: 'Search symbols in the active editor.',
    id: 'workspace.gotoSymbol',
    keepsPaletteOpen: true,
    keys: [
      {
        chord: ['Mod+Shift+O'],
        preventDefault: true,
        vscodeCommandId: 'workbench.action.gotoSymbol',
      },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['fileBackedTab'],
    title: 'Go to symbol in editor',
    vscodeCommandIds: ['workbench.action.gotoSymbol'],
  }),
  'workspace.showAllEditors': defineMetadata({
    category: 'Workspace',
    description: 'Search open editor tabs.',
    id: 'workspace.showAllEditors',
    keepsPaletteOpen: true,
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Show all editors',
    vscodeCommandIds: ['workbench.action.showAllEditors'],
  }),
  'workspace.saveFile': defineMetadata({
    category: 'Workspace',
    description: 'Save the active editor.',
    id: 'workspace.saveFile',
    keys: [
      { chord: ['Mod+S'], preventDefault: true, vscodeCommandId: 'workbench.action.files.save' },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'file-operation',
    when: ['saveableTab', 'workspaceMutable'],
    title: 'Save',
    vscodeCommandIds: ['workbench.action.files.save'],
  }),
  'workspace.saveAllFiles': defineMetadata({
    category: 'Workspace',
    description: 'Save all dirty editors.',
    id: 'workspace.saveAllFiles',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'file-operation',
    when: ['workspaceOpen', 'workspaceMutable'],
    title: 'Save all',
    vscodeCommandIds: ['workbench.action.files.saveAll'],
  }),
  'workspace.compareWithSaved': defineMetadata({
    category: 'Workspace',
    description: 'Diff the active editor against the file on disk.',
    id: 'workspace.compareWithSaved',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['fileBackedTab'],
    title: 'Compare with saved',
    vscodeCommandIds: ['workbench.files.action.compareWithSaved'],
  }),
  'workspace.openFileAtHead': defineMetadata({
    category: 'Workspace',
    description: 'Open the committed version of the active file, read-only.',
    id: 'workspace.openFileAtHead',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['fileBackedTab'],
    title: 'Open file at HEAD',
    vscodeCommandIds: ['git.openFile'],
  }),
  'workspace.revertFile': defineMetadata({
    category: 'Workspace',
    description: 'Reload the active editor from disk.',
    id: 'workspace.revertFile',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'file-operation',
    when: ['fileBackedTab'],
    title: 'Revert file',
    vscodeCommandIds: ['workbench.action.files.revert'],
  }),
  'workspace.reopenClosedEditor': defineMetadata({
    category: 'Workspace',
    description: 'Reopen the most recently closed editor tab.',
    id: 'workspace.reopenClosedEditor',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Reopen closed editor',
    vscodeCommandIds: ['workbench.action.reopenClosedEditor'],
  }),
  'workspace.toggleSidebarVisibility': defineMetadata({
    category: 'Workspace',
    description: 'Show or hide the Files pane.',
    id: 'workspace.toggleSidebarVisibility',
    keys: [
      {
        chord: ['Mod+B'],
        preventDefault: true,
        vscodeCommandId: 'workbench.action.toggleSidebarVisibility',
      },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Toggle Files pane',
    vscodeCommandIds: ['workbench.action.toggleSidebarVisibility'],
  }),
  'workspace.togglePanel': defineMetadata({
    category: 'Workspace',
    description: 'Show or hide the active workspace panel.',
    id: 'workspace.togglePanel',
    keys: [
      {
        chord: ['Mod+J'],
        preventDefault: true,
        vscodeCommandId: 'workbench.action.togglePanel',
      },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Toggle panel',
    vscodeCommandIds: ['workbench.action.togglePanel'],
  }),
  'workspace.focusFirstEditorGroup': defineMetadata({
    category: 'Workspace',
    description: 'Focus the primary editor group.',
    id: 'workspace.focusFirstEditorGroup',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Focus first editor group',
    vscodeCommandIds: ['workbench.action.focusFirstEditorGroup'],
  }),
  'workspace.focusSecondEditorGroup': defineMetadata({
    category: 'Workspace',
    description: 'Focus the current editor group in single-group mode.',
    id: 'workspace.focusSecondEditorGroup',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Focus second editor group',
    vscodeCommandIds: ['workbench.action.focusSecondEditorGroup'],
  }),
  'workspace.focusThirdEditorGroup': defineMetadata({
    category: 'Workspace',
    description: 'Focus the current editor group in single-group mode.',
    id: 'workspace.focusThirdEditorGroup',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Focus third editor group',
    vscodeCommandIds: ['workbench.action.focusThirdEditorGroup'],
  }),
  'workspace.focusEditor': defineMetadata({
    category: 'Workspace',
    description: 'Move keyboard focus to the editor.',
    id: 'workspace.focusEditor',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Focus editor',
  }),
  'workspace.focusFileTree': defineMetadata({
    category: 'Workspace',
    description: 'Move keyboard focus to the file tree.',
    id: 'workspace.focusFileTree',
    keys: [{ chord: ['Mod+Shift+E'], preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Focus file tree',
  }),
  'workspace.findInFileTree': defineMetadata({
    category: 'Workspace',
    description: 'Filter the loaded files in the file tree.',
    id: 'workspace.findInFileTree',
    keys: [{ chord: ['Mod+F'], pane: 'file-tree', preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Filter files in tree',
  }),
  'workspace.revealActiveFileInTree': defineMetadata({
    category: 'Workspace',
    description: 'Focus and reveal the active editor file in the file tree.',
    id: 'workspace.revealActiveFileInTree',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['fileBackedTab'],
    title: 'Reveal active file in tree',
  }),
  'workspace.focusGit': defineMetadata({
    category: 'Workspace',
    description: 'Move keyboard focus to the Git panel.',
    id: 'workspace.focusGit',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Focus Git',
  }),
  'workspace.copyAddress': defineMetadata({
    category: 'Workspace',
    description:
      'Copy a link to exactly where you are — no absolute paths, no dev-only parameters.',
    id: 'workspace.copyAddress',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: ['workspaceOpen'],
    title: 'Copy address',
  }),
  'workspace.navigateBack': defineMetadata({
    category: 'Workspace',
    description: 'Go back to the previous document.',
    id: 'workspace.navigateBack',
    keys: [{ chord: ['Mod+['] }, { chord: ['Control+K', 'B'], platforms: ['tui'] }],
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Back',
  }),
  'workspace.navigateForward': defineMetadata({
    category: 'Workspace',
    description: 'Go forward again.',
    id: 'workspace.navigateForward',
    keys: [{ chord: ['Mod+]'] }, { chord: ['Control+K', 'N'], platforms: ['tui'] }],
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Forward',
  }),
  'workspace.revealChat': defineMetadata({
    category: 'Workspace',
    description: 'Bring the chat composer on screen.',
    id: 'workspace.revealChat',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Show chat',
  }),
  'workspace.revealTerminal': defineMetadata({
    category: 'Workspace',
    description: 'Bring the workbench terminal on screen.',
    id: 'workspace.revealTerminal',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Show terminal',
  }),
  'workspace.closeCurrentTab': defineMetadata({
    category: 'Workspace',
    description: 'Close the selected editor tab.',
    id: 'workspace.closeCurrentTab',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Close current tab',
    vscodeCommandIds: ['workbench.action.closeActiveEditor'],
  }),
  'workspace.toggleDiffViewMode': defineMetadata({
    category: 'Workspace',
    description: 'Switch the active diff viewer between split and unified modes.',
    id: 'workspace.toggleDiffViewMode',
    keys: [{ chord: ['Mod+Shift+D'] }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: ['workspaceOpen'],
    title: 'Toggle diff view mode',
  }),
  'workspace.toggleUiMode': defineMetadata({
    category: 'Workspace',
    description: 'Switch between the Workbench and Chat layouts.',
    id: 'workspace.toggleUiMode',
    keys: [{ chord: ['Mod+Shift+M'], preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Toggle Chat mode',
  }),
  'workspace.showChatMode': defineMetadata({
    category: 'Workspace',
    description: 'Show sessions, chat, and tools in the chat layout.',
    id: 'workspace.showChatMode',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Chat mode',
  }),
  'workspace.showWorkbenchMode': defineMetadata({
    category: 'Workspace',
    description: 'Show the editor-centred workbench layout.',
    id: 'workspace.showWorkbenchMode',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Workbench mode',
  }),
  'workspace.selectColorMode': defineMetadata({
    category: 'Appearance',
    description: 'Pick light, dark, or system color mode.',
    id: 'workspace.selectColorMode',
    keepsPaletteOpen: true,
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Choose color mode',
  }),
  'workspace.selectColorTheme': defineMetadata({
    category: 'Appearance',
    description: 'Pick the editor color theme from the bundled VSCode themes.',
    id: 'workspace.selectColorTheme',
    keepsPaletteOpen: true,
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Choose color theme',
  }),
  'workspace.setDarkTheme': defineMetadata({
    category: 'Appearance',
    description: 'Use dark color mode.',
    hiddenInPalette: true,
    id: 'workspace.setDarkTheme',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: [],
    title: 'Dark color mode',
  }),
  'workspace.setLightTheme': defineMetadata({
    category: 'Appearance',
    description: 'Use light color mode.',
    hiddenInPalette: true,
    id: 'workspace.setLightTheme',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: [],
    title: 'Light color mode',
  }),
  'workspace.setSystemTheme': defineMetadata({
    category: 'Appearance',
    description: 'Follow the system color mode.',
    hiddenInPalette: true,
    id: 'workspace.setSystemTheme',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: [],
    title: 'System color mode',
  }),
  'workspace.toggleWallpaper': defineMetadata({
    category: 'Appearance',
    description: 'Show or hide the background image or video.',
    id: 'workspace.toggleWallpaper',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: [],
    title: 'Toggle wallpaper',
  }),
  'workspace.newSession': defineMetadata({
    category: 'Workspace',
    description: 'Start a new chat session in the active project.',
    hiddenInPalette: true,
    id: 'workspace.newSession',
    keys: [{ chord: ['Mod+Alt+N'], preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: ['workspaceOpen', 'chatMode'],
    title: 'New session',
  }),
  'workspace.nextSession': defineMetadata({
    category: 'Workspace',
    description: 'Move to the next session in the rail.',
    hiddenInPalette: true,
    id: 'workspace.nextSession',
    keys: [{ chord: ['Mod+Alt+]'], preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen', 'chatMode'],
    title: 'Next session',
  }),
  'workspace.previousSession': defineMetadata({
    category: 'Workspace',
    description: 'Move to the previous session in the rail.',
    hiddenInPalette: true,
    id: 'workspace.previousSession',
    keys: [{ chord: ['Mod+Alt+['], preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen', 'chatMode'],
    title: 'Previous session',
  }),
  'workspace.toggleSessionRail': defineMetadata({
    category: 'Workspace',
    description: 'Show or hide the list of sessions.',
    hiddenInPalette: true,
    id: 'workspace.toggleSessionRail',
    keys: [{ chord: ['Mod+Alt+B'], preventDefault: true }],
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen', 'chatMode'],
    title: 'Toggle session rail',
  }),
}
export function sessionJumpMetadata(position: SessionJumpPosition) {
  return defineMetadata({
    category: 'Workspace',
    description: `Put session ${position} in the rail on the stage.`,
    hiddenInPalette: true,
    id: sessionJumpCommandId(position),
    keys: [{ chord: [`Mod+Alt+${position}`], preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen', 'chatMode'],
    title: `Go to session ${position}`,
  })
}
