const CHROME_TAB_CLOSE_BURST_MS = 45
const CHROME_TAB_CLOSE_BURST_EASE = 'cubic-bezier(0.23, 1, 0.32, 1)'
export const CHROME_TAB_TRANSITION = `flex-basis ${CHROME_TAB_CLOSE_BURST_MS}ms ${CHROME_TAB_CLOSE_BURST_EASE}, margin-left ${CHROME_TAB_CLOSE_BURST_MS}ms ${CHROME_TAB_CLOSE_BURST_EASE}, max-width ${CHROME_TAB_CLOSE_BURST_MS}ms ${CHROME_TAB_CLOSE_BURST_EASE}, min-width ${CHROME_TAB_CLOSE_BURST_MS}ms ${CHROME_TAB_CLOSE_BURST_EASE}, opacity ${CHROME_TAB_CLOSE_BURST_MS}ms ${CHROME_TAB_CLOSE_BURST_EASE}, width ${CHROME_TAB_CLOSE_BURST_MS}ms ${CHROME_TAB_CLOSE_BURST_EASE}`
