export const CHAT_MESSAGE_CACHE_LIMIT = 2_000
export const CHAT_CHECKPOINT_CACHE_LIMIT = 500
export const CHAT_PROPOSED_PLAN_CACHE_LIMIT = 200
export const CHAT_ACTIVITY_CACHE_LIMIT = 500

export const THREAD_DETAIL_SUBSCRIPTION_IDLE_EVICTION_MS = 15 * 60 * 1000
export const MAX_CACHED_THREAD_DETAIL_SUBSCRIPTIONS = 32
export const SIDEBAR_THREAD_DETAIL_PREWARM_LIMIT = 10
