import { hotkeyPresetId } from '@workspace/tiling/utils/layout-ids'
import {
  CLOSE_ACTIVE_SURFACE_COMMAND_ID,
  BACKGROUND_ACTIVE_SURFACE_COMMAND_ID,
  COLLAPSE_ACTIVE_WINDOW_COMMAND_ID,
  EXPAND_ACTIVE_WINDOW_COMMAND_ID,
  FOCUS_WINDOW_BOTTOM_COMMAND_ID,
  FOCUS_WINDOW_LEFT_COMMAND_ID,
  FOCUS_WINDOW_RIGHT_COMMAND_ID,
  FOCUS_WINDOW_TOP_COMMAND_ID,
  FULLSCREEN_ACTIVE_WINDOW_COMMAND_ID,
  LEFT_HALF_ACTIVE_WINDOW_COMMAND_ID,
  MAXIMIZE_ACTIVE_WINDOW_COMMAND_ID,
  MOVE_ACTIVE_WINDOW_BOTTOM_COMMAND_ID,
  MOVE_ACTIVE_WINDOW_LEFT_COMMAND_ID,
  MOVE_ACTIVE_WINDOW_RIGHT_COMMAND_ID,
  MOVE_ACTIVE_WINDOW_TOP_COMMAND_ID,
  NEXT_SURFACE_IN_WINDOW_COMMAND_ID,
  PREVIOUS_SURFACE_IN_WINDOW_COMMAND_ID,
  REASONABLE_SIZE_ACTIVE_WINDOW_COMMAND_ID,
  RESIZE_ACTIVE_SPLIT_BOTTOM_COMMAND_ID,
  RESIZE_ACTIVE_SPLIT_LEFT_COMMAND_ID,
  RESIZE_ACTIVE_SPLIT_RIGHT_COMMAND_ID,
  RESIZE_ACTIVE_SPLIT_TOP_COMMAND_ID,
  RESTORE_ACTIVE_WINDOW_COMMAND_ID,
  RIGHT_HALF_ACTIVE_WINDOW_COMMAND_ID,
  SPLIT_ACTIVE_WINDOW_BOTTOM_COMMAND_ID,
  SPLIT_ACTIVE_WINDOW_LEFT_COMMAND_ID,
  SPLIT_ACTIVE_WINDOW_RIGHT_COMMAND_ID,
  SPLIT_ACTIVE_WINDOW_TOP_COMMAND_ID,
  TEAR_ACTIVE_SURFACE_RIGHT_COMMAND_ID,
} from '@workspace/tiling/utils/layout-command-catalog'
import type { WindowManagementHotkeyPreset } from '@workspace/tiling/utils/layout-types'

export const PLATFORM_HOTKEY_PRESET_ID = hotkeyPresetId('platform')
export const VSCODE_HOTKEY_PRESET_ID = hotkeyPresetId('vscode')
export const HYPRLAND_I3_HOTKEY_PRESET_ID = hotkeyPresetId('hyprland-i3')

export const DEFAULT_WINDOW_MANAGEMENT_HOTKEY_PRESETS = [
  {
    bindings: {
      [CLOSE_ACTIVE_SURFACE_COMMAND_ID]: 'Alt+Shift+W',
      [FULLSCREEN_ACTIVE_WINDOW_COMMAND_ID]: 'Alt+Shift+F',
      [MAXIMIZE_ACTIVE_WINDOW_COMMAND_ID]: 'Alt+Shift+M',
      [LEFT_HALF_ACTIVE_WINDOW_COMMAND_ID]: 'Alt+Shift+1',
      [RIGHT_HALF_ACTIVE_WINDOW_COMMAND_ID]: 'Alt+Shift+2',
      [REASONABLE_SIZE_ACTIVE_WINDOW_COMMAND_ID]: 'Alt+Shift+Z',
      [BACKGROUND_ACTIVE_SURFACE_COMMAND_ID]: 'Alt+Shift+B',
      [COLLAPSE_ACTIVE_WINDOW_COMMAND_ID]: 'Alt+Shift+C',
      [EXPAND_ACTIVE_WINDOW_COMMAND_ID]: 'Alt+Shift+E',
      [FOCUS_WINDOW_BOTTOM_COMMAND_ID]: 'Ctrl+Alt+Shift+ArrowDown',
      [FOCUS_WINDOW_LEFT_COMMAND_ID]: 'Ctrl+Alt+Shift+ArrowLeft',
      [FOCUS_WINDOW_RIGHT_COMMAND_ID]: 'Ctrl+Alt+Shift+ArrowRight',
      [FOCUS_WINDOW_TOP_COMMAND_ID]: 'Ctrl+Alt+Shift+ArrowUp',
      [MOVE_ACTIVE_WINDOW_BOTTOM_COMMAND_ID]: 'Alt+Shift+ArrowDown',
      [MOVE_ACTIVE_WINDOW_LEFT_COMMAND_ID]: 'Alt+Shift+ArrowLeft',
      [MOVE_ACTIVE_WINDOW_RIGHT_COMMAND_ID]: 'Alt+Shift+ArrowRight',
      [MOVE_ACTIVE_WINDOW_TOP_COMMAND_ID]: 'Alt+Shift+ArrowUp',
      [NEXT_SURFACE_IN_WINDOW_COMMAND_ID]: 'Alt+Shift+N',
      [PREVIOUS_SURFACE_IN_WINDOW_COMMAND_ID]: 'Alt+Shift+P',
      [RESIZE_ACTIVE_SPLIT_BOTTOM_COMMAND_ID]: 'Ctrl+Alt+ArrowDown',
      [RESIZE_ACTIVE_SPLIT_LEFT_COMMAND_ID]: 'Ctrl+Alt+ArrowLeft',
      [RESIZE_ACTIVE_SPLIT_RIGHT_COMMAND_ID]: 'Ctrl+Alt+ArrowRight',
      [RESIZE_ACTIVE_SPLIT_TOP_COMMAND_ID]: 'Ctrl+Alt+ArrowUp',
      [RESTORE_ACTIVE_WINDOW_COMMAND_ID]: 'Alt+Shift+R',
      [SPLIT_ACTIVE_WINDOW_BOTTOM_COMMAND_ID]: 'Alt+Shift+J',
      [SPLIT_ACTIVE_WINDOW_LEFT_COMMAND_ID]: 'Alt+Shift+A',
      [SPLIT_ACTIVE_WINDOW_RIGHT_COMMAND_ID]: 'Alt+Shift+D',
      [SPLIT_ACTIVE_WINDOW_TOP_COMMAND_ID]: 'Alt+Shift+K',
      [TEAR_ACTIVE_SURFACE_RIGHT_COMMAND_ID]: 'Alt+Shift+T',
    },
    id: PLATFORM_HOTKEY_PRESET_ID,
    source: 'platform',
    title: 'Platform',
  },
  {
    bindings: {
      [CLOSE_ACTIVE_SURFACE_COMMAND_ID]: 'Ctrl+W',
      [COLLAPSE_ACTIVE_WINDOW_COMMAND_ID]: 'Ctrl+K Ctrl+C',
      [EXPAND_ACTIVE_WINDOW_COMMAND_ID]: 'Ctrl+K Ctrl+E',
      [FULLSCREEN_ACTIVE_WINDOW_COMMAND_ID]: 'Ctrl+K Ctrl+F',
      [MAXIMIZE_ACTIVE_WINDOW_COMMAND_ID]: 'Ctrl+K Ctrl+M',
      [NEXT_SURFACE_IN_WINDOW_COMMAND_ID]: 'Ctrl+PageDown',
      [PREVIOUS_SURFACE_IN_WINDOW_COMMAND_ID]: 'Ctrl+PageUp',
      [RESTORE_ACTIVE_WINDOW_COMMAND_ID]: 'Ctrl+K Ctrl+R',
      [SPLIT_ACTIVE_WINDOW_BOTTOM_COMMAND_ID]: 'Ctrl+K Ctrl+\\',
      [SPLIT_ACTIVE_WINDOW_RIGHT_COMMAND_ID]: 'Ctrl+\\',
    },
    id: VSCODE_HOTKEY_PRESET_ID,
    source: 'vscode',
    title: 'VS Code',
  },
  {
    bindings: {
      [CLOSE_ACTIVE_SURFACE_COMMAND_ID]: 'Mod+Shift+Q',
      [COLLAPSE_ACTIVE_WINDOW_COMMAND_ID]: 'Mod+Shift+C',
      [EXPAND_ACTIVE_WINDOW_COMMAND_ID]: 'Mod+Shift+E',
      [FOCUS_WINDOW_BOTTOM_COMMAND_ID]: 'Mod+J',
      [FOCUS_WINDOW_LEFT_COMMAND_ID]: 'Mod+H',
      [FOCUS_WINDOW_RIGHT_COMMAND_ID]: 'Mod+L',
      [FOCUS_WINDOW_TOP_COMMAND_ID]: 'Mod+K',
      [FULLSCREEN_ACTIVE_WINDOW_COMMAND_ID]: 'Mod+Shift+F',
      [LEFT_HALF_ACTIVE_WINDOW_COMMAND_ID]: 'Mod+ArrowLeft',
      [MAXIMIZE_ACTIVE_WINDOW_COMMAND_ID]: 'Mod+F',
      [MOVE_ACTIVE_WINDOW_BOTTOM_COMMAND_ID]: 'Mod+Shift+J',
      [MOVE_ACTIVE_WINDOW_LEFT_COMMAND_ID]: 'Mod+Shift+H',
      [MOVE_ACTIVE_WINDOW_RIGHT_COMMAND_ID]: 'Mod+Shift+L',
      [MOVE_ACTIVE_WINDOW_TOP_COMMAND_ID]: 'Mod+Shift+K',
      [RIGHT_HALF_ACTIVE_WINDOW_COMMAND_ID]: 'Mod+ArrowRight',
      [SPLIT_ACTIVE_WINDOW_BOTTOM_COMMAND_ID]: 'Mod+V',
      [SPLIT_ACTIVE_WINDOW_RIGHT_COMMAND_ID]: 'Mod+Alt+H',
    },
    id: HYPRLAND_I3_HOTKEY_PRESET_ID,
    source: 'hyprland-i3',
    title: 'Hyprland / i3',
  },
] as const satisfies readonly WindowManagementHotkeyPreset[]

export function defaultWindowManagementHotkeyPresets() {
  return DEFAULT_WINDOW_MANAGEMENT_HOTKEY_PRESETS
}

export function defaultHotkeyPresetsById() {
  const presetsById: Record<string, WindowManagementHotkeyPreset> = {}

  for (const preset of DEFAULT_WINDOW_MANAGEMENT_HOTKEY_PRESETS) {
    presetsById[preset.id] = preset
  }

  return presetsById
}
