import {
  ArrowArcLeftIcon,
  ArrowArcRightIcon,
  ArrowLineDownIcon,
  ArrowLineUpIcon,
  ArrowSquareOutIcon,
  ArrowsOutLineVerticalIcon,
  ChatTextIcon,
  CopySimpleIcon,
  CursorClickIcon,
  LinkIcon,
  MagnifyingGlassIcon,
  SelectionIcon,
  SwapIcon,
  TextIndentIcon,
  TextOutdentIcon,
  TrashIcon,
} from '@phosphor-icons/react'

import { defineEditorCommand } from './define-command'

export const editorCommands = [
  defineEditorCommand({
    icon: ArrowArcLeftIcon,
    id: 'undo',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Mod+Z'], vscodeCommandId: 'undo' }],
    title: 'Undo',
    vscodeCommandIds: ['undo'],
  }),
  defineEditorCommand({
    icon: ArrowArcRightIcon,
    id: 'redo',
    undoCategory: 'text-edit',
    keys: [
      { chord: ['Mod+Shift+Z'], vscodeCommandId: 'redo' },
      { chord: ['Control+Y'], platforms: ['windows', 'linux'], vscodeCommandId: 'redo' },
    ],
    title: 'Redo',
    vscodeCommandIds: ['redo'],
  }),
  defineEditorCommand({
    icon: MagnifyingGlassIcon,
    id: 'find',
    undoCategory: 'view-only',
    keys: [{ chord: ['Mod+F'], vscodeCommandId: 'actions.find' }],
    title: 'Find',
    vscodeCommandIds: ['actions.find'],
  }),
  defineEditorCommand({
    icon: SwapIcon,
    id: 'findReplace',
    undoCategory: 'view-only',
    keys: [
      {
        chord: ['Mod+H'],
        platforms: ['windows', 'linux'],
        vscodeCommandId: 'editor.action.startFindReplaceAction',
      },
      {
        chord: ['Mod+Alt+F'],
        platforms: ['mac'],
        vscodeCommandId: 'editor.action.startFindReplaceAction',
      },
    ],
    title: 'Find and replace',
    vscodeCommandIds: ['editor.action.startFindReplaceAction'],
  }),
  defineEditorCommand({
    icon: MagnifyingGlassIcon,
    id: 'findNext',
    undoCategory: 'view-only',
    keys: [
      { chord: ['F3'], vscodeCommandId: 'editor.action.nextMatchFindAction' },
      {
        chord: ['Mod+G'],
        platforms: ['mac'],
        vscodeCommandId: 'editor.action.nextMatchFindAction',
      },
    ],
    title: 'Find next',
    vscodeCommandIds: ['editor.action.nextMatchFindAction'],
  }),
  defineEditorCommand({
    icon: MagnifyingGlassIcon,
    id: 'findPrevious',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Shift+F3'], vscodeCommandId: 'editor.action.previousMatchFindAction' },
      {
        chord: ['Mod+Shift+G'],
        platforms: ['mac'],
        vscodeCommandId: 'editor.action.previousMatchFindAction',
      },
    ],
    title: 'Find previous',
    vscodeCommandIds: ['editor.action.previousMatchFindAction'],
  }),
  defineEditorCommand({
    icon: ArrowSquareOutIcon,
    id: 'goToDefinition',
    undoCategory: 'view-only',
    title: 'Go to definition',
    vscodeCommandIds: ['editor.action.revealDefinition'],
  }),
  defineEditorCommand({
    hiddenInPalette: true,
    id: 'editor.action.goToImplementation',
    undoCategory: 'view-only',
    title: 'Go to implementation',
    vscodeCommandIds: ['editor.action.goToImplementation'],
  }),
  defineEditorCommand({
    hiddenInPalette: true,
    id: 'editor.action.goToTypeDefinition',
    undoCategory: 'view-only',
    title: 'Go to type definition',
    vscodeCommandIds: ['editor.action.goToTypeDefinition'],
  }),
  defineEditorCommand({
    hiddenInPalette: true,
    id: 'editor.action.peekDefinition',
    undoCategory: 'view-only',
    title: 'Peek definition',
    vscodeCommandIds: ['editor.action.peekDefinition'],
  }),
  defineEditorCommand({
    hiddenInPalette: true,
    id: 'editor.action.revealDefinitionAside',
    undoCategory: 'view-only',
    title: 'Open definition to the side',
    vscodeCommandIds: ['editor.action.revealDefinitionAside'],
  }),
  defineEditorCommand({
    icon: ChatTextIcon,
    id: 'editor.action.showHover',
    undoCategory: 'view-only',
    title: 'Show hover',
    vscodeCommandIds: ['editor.action.showHover'],
  }),
  defineEditorCommand({
    icon: LinkIcon,
    id: 'editor.action.goToReferences',
    undoCategory: 'view-only',
    keys: [
      {
        chord: ['Shift+F12'],
        preventDefault: true,
        vscodeCommandId: 'editor.action.goToReferences',
      },
    ],
    title: 'Find references',
    vscodeCommandIds: ['editor.action.goToReferences'],
  }),
  defineEditorCommand({
    id: 'closeFind',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Escape'], vscodeCommandId: 'closeFindWidget' },
      { chord: ['Shift+Escape'], vscodeCommandId: 'closeFindWidget' },
    ],
    title: 'Close find',
    vscodeCommandIds: ['closeFindWidget'],
  }),
  defineEditorCommand({
    id: 'toggleFindCaseSensitive',
    undoCategory: 'view-only',
    keys: [
      {
        chord: ['Alt+C'],
        platforms: ['windows', 'linux'],
        vscodeCommandId: 'toggleFindCaseSensitive',
      },
      { chord: ['Mod+Alt+C'], platforms: ['mac'], vscodeCommandId: 'toggleFindCaseSensitive' },
    ],
    title: 'Toggle case sensitive find',
    vscodeCommandIds: ['toggleFindCaseSensitive'],
  }),
  defineEditorCommand({
    id: 'toggleFindWholeWord',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Alt+W'], platforms: ['windows', 'linux'], vscodeCommandId: 'toggleFindWholeWord' },
      { chord: ['Mod+Alt+W'], platforms: ['mac'], vscodeCommandId: 'toggleFindWholeWord' },
    ],
    title: 'Toggle whole word find',
    vscodeCommandIds: ['toggleFindWholeWord'],
  }),
  defineEditorCommand({
    id: 'toggleFindRegex',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Alt+R'], platforms: ['windows', 'linux'], vscodeCommandId: 'toggleFindRegex' },
      { chord: ['Mod+Alt+R'], platforms: ['mac'], vscodeCommandId: 'toggleFindRegex' },
    ],
    title: 'Toggle regex find',
    vscodeCommandIds: ['toggleFindRegex'],
  }),
  defineEditorCommand({
    id: 'toggleFindInSelection',
    undoCategory: 'view-only',
    keys: [
      {
        chord: ['Alt+L'],
        platforms: ['windows', 'linux'],
        vscodeCommandId: 'toggleFindInSelection',
      },
      { chord: ['Mod+Alt+L'], platforms: ['mac'], vscodeCommandId: 'toggleFindInSelection' },
    ],
    title: 'Toggle find in selection',
    vscodeCommandIds: ['toggleFindInSelection'],
  }),
  defineEditorCommand({
    id: 'togglePreserveCase',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Alt+P'], platforms: ['windows', 'linux'], vscodeCommandId: 'togglePreserveCase' },
      { chord: ['Mod+Alt+P'], platforms: ['mac'], vscodeCommandId: 'togglePreserveCase' },
    ],
    title: 'Toggle preserve case',
    vscodeCommandIds: ['togglePreserveCase'],
  }),
  defineEditorCommand({
    icon: SwapIcon,
    id: 'replaceOne',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Mod+Shift+1'], vscodeCommandId: 'editor.action.replaceOne' }],
    title: 'Replace',
    vscodeCommandIds: ['editor.action.replaceOne'],
  }),
  defineEditorCommand({
    icon: SwapIcon,
    id: 'replaceAll',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Mod+Alt+Enter'], vscodeCommandId: 'editor.action.replaceAll' }],
    title: 'Replace all',
    vscodeCommandIds: ['editor.action.replaceAll'],
  }),
  defineEditorCommand({
    icon: SelectionIcon,
    id: 'selectAllMatches',
    undoCategory: 'view-only',
    keys: [{ chord: ['Alt+Enter'], vscodeCommandId: 'editor.action.selectAllMatches' }],
    title: 'Select all matches',
    vscodeCommandIds: ['editor.action.selectAllMatches'],
  }),
  defineEditorCommand({
    icon: SelectionIcon,
    id: 'selectAll',
    undoCategory: 'view-only',
    keys: [{ chord: ['Mod+A'], vscodeCommandId: 'editor.action.selectAll' }],
    title: 'Select all',
    vscodeCommandIds: ['editor.action.selectAll'],
  }),
  defineEditorCommand({
    icon: CursorClickIcon,
    id: 'addNextOccurrence',
    undoCategory: 'view-only',
    keys: [{ chord: ['Mod+D'], vscodeCommandId: 'editor.action.addSelectionToNextFindMatch' }],
    title: 'Add next occurrence',
    vscodeCommandIds: ['editor.action.addSelectionToNextFindMatch'],
  }),
  defineEditorCommand({
    icon: CursorClickIcon,
    id: 'clearSecondarySelections',
    undoCategory: 'view-only',
    title: 'Clear secondary selections',
    vscodeCommandIds: ['removeSecondaryCursors'],
  }),
  defineEditorCommand({
    id: 'deleteWordLeft',
    undoCategory: 'text-edit',
    keys: [
      { chord: ['Alt+Backspace'], platforms: ['mac'], vscodeCommandId: 'deleteWordLeft' },
      {
        chord: ['Mod+Backspace'],
        platforms: ['windows', 'linux'],
        vscodeCommandId: 'deleteWordLeft',
      },
    ],
    title: 'Delete word left',
    vscodeCommandIds: ['deleteWordLeft'],
  }),
  defineEditorCommand({
    id: 'deleteWordRight',
    undoCategory: 'text-edit',
    keys: [
      { chord: ['Alt+Delete'], platforms: ['mac'], vscodeCommandId: 'deleteWordRight' },
      {
        chord: ['Mod+Delete'],
        platforms: ['windows', 'linux'],
        vscodeCommandId: 'deleteWordRight',
      },
    ],
    title: 'Delete word right',
    vscodeCommandIds: ['deleteWordRight'],
  }),
  defineEditorCommand({
    icon: TrashIcon,
    id: 'editor.action.deleteLines',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Mod+Shift+K'], vscodeCommandId: 'editor.action.deleteLines' }],
    title: 'Delete line',
    vscodeCommandIds: ['editor.action.deleteLines'],
  }),
  defineEditorCommand({
    icon: CopySimpleIcon,
    id: 'editor.action.copyLinesUpAction',
    undoCategory: 'text-edit',
    keys: [
      {
        chord: ['Alt+Shift+ArrowUp'],
        platforms: ['mac', 'windows'],
        vscodeCommandId: 'editor.action.copyLinesUpAction',
      },
      {
        chord: ['Mod+Alt+Shift+ArrowUp'],
        platforms: ['linux'],
        vscodeCommandId: 'editor.action.copyLinesUpAction',
      },
    ],
    title: 'Copy line up',
    vscodeCommandIds: ['editor.action.copyLinesUpAction'],
  }),
  defineEditorCommand({
    icon: CopySimpleIcon,
    id: 'editor.action.copyLinesDownAction',
    undoCategory: 'text-edit',
    keys: [
      {
        chord: ['Alt+Shift+ArrowDown'],
        platforms: ['mac', 'windows'],
        vscodeCommandId: 'editor.action.copyLinesDownAction',
      },
      {
        chord: ['Mod+Alt+Shift+ArrowDown'],
        platforms: ['linux'],
        vscodeCommandId: 'editor.action.copyLinesDownAction',
      },
    ],
    title: 'Copy line down',
    vscodeCommandIds: ['editor.action.copyLinesDownAction'],
  }),
  defineEditorCommand({
    icon: ArrowsOutLineVerticalIcon,
    id: 'editor.action.moveLinesUpAction',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Alt+ArrowUp'], vscodeCommandId: 'editor.action.moveLinesUpAction' }],
    title: 'Move line up',
    vscodeCommandIds: ['editor.action.moveLinesUpAction'],
  }),
  defineEditorCommand({
    icon: ArrowsOutLineVerticalIcon,
    id: 'editor.action.moveLinesDownAction',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Alt+ArrowDown'], vscodeCommandId: 'editor.action.moveLinesDownAction' }],
    title: 'Move line down',
    vscodeCommandIds: ['editor.action.moveLinesDownAction'],
  }),
  defineEditorCommand({
    icon: ArrowLineUpIcon,
    id: 'editor.action.insertLineBefore',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Mod+Shift+Enter'], vscodeCommandId: 'editor.action.insertLineBefore' }],
    title: 'Insert line above',
    vscodeCommandIds: ['editor.action.insertLineBefore'],
  }),
  defineEditorCommand({
    icon: ArrowLineDownIcon,
    id: 'editor.action.insertLineAfter',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Mod+Enter'], vscodeCommandId: 'editor.action.insertLineAfter' }],
    title: 'Insert line below',
    vscodeCommandIds: ['editor.action.insertLineAfter'],
  }),
  defineEditorCommand({
    icon: ChatTextIcon,
    id: 'editor.action.commentLine',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Mod+/'], vscodeCommandId: 'editor.action.commentLine' }],
    title: 'Toggle line comment',
    vscodeCommandIds: ['editor.action.commentLine'],
  }),
  defineEditorCommand({
    icon: ChatTextIcon,
    id: 'editor.action.blockComment',
    undoCategory: 'text-edit',
    keys: [
      {
        chord: ['Alt+Shift+A'],
        platforms: ['mac', 'windows'],
        vscodeCommandId: 'editor.action.blockComment',
      },
      {
        chord: ['Mod+Shift+A'],
        platforms: ['linux'],
        vscodeCommandId: 'editor.action.blockComment',
      },
    ],
    title: 'Toggle block comment',
    vscodeCommandIds: ['editor.action.blockComment'],
  }),
  defineEditorCommand({
    icon: TextIndentIcon,
    id: 'editor.action.indentLines',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Mod+]'], vscodeCommandId: 'editor.action.indentLines' }],
    title: 'Indent line',
    vscodeCommandIds: ['editor.action.indentLines'],
  }),
  defineEditorCommand({
    icon: TextOutdentIcon,
    id: 'editor.action.outdentLines',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Mod+['], vscodeCommandId: 'editor.action.outdentLines' }],
    title: 'Outdent line',
    vscodeCommandIds: ['editor.action.outdentLines'],
  }),
  defineEditorCommand({
    icon: CursorClickIcon,
    id: 'editor.action.insertCursorAbove',
    undoCategory: 'view-only',
    keys: [
      {
        chord: ['Mod+Alt+ArrowUp'],
        platforms: ['mac', 'windows'],
        vscodeCommandId: 'editor.action.insertCursorAbove',
      },
      {
        chord: ['Alt+Shift+ArrowUp'],
        platforms: ['linux'],
        vscodeCommandId: 'editor.action.insertCursorAbove',
      },
      {
        chord: ['Mod+Shift+ArrowUp'],
        platforms: ['linux'],
        vscodeCommandId: 'editor.action.insertCursorAbove',
      },
    ],
    title: 'Add cursor above',
    vscodeCommandIds: ['editor.action.insertCursorAbove'],
  }),
  defineEditorCommand({
    icon: CursorClickIcon,
    id: 'editor.action.insertCursorBelow',
    undoCategory: 'view-only',
    keys: [
      {
        chord: ['Mod+Alt+ArrowDown'],
        platforms: ['mac', 'windows'],
        vscodeCommandId: 'editor.action.insertCursorBelow',
      },
      {
        chord: ['Alt+Shift+ArrowDown'],
        platforms: ['linux'],
        vscodeCommandId: 'editor.action.insertCursorBelow',
      },
      {
        chord: ['Mod+Shift+ArrowDown'],
        platforms: ['linux'],
        vscodeCommandId: 'editor.action.insertCursorBelow',
      },
    ],
    title: 'Add cursor below',
    vscodeCommandIds: ['editor.action.insertCursorBelow'],
  }),
  defineEditorCommand({
    icon: SelectionIcon,
    id: 'editor.action.selectHighlights',
    undoCategory: 'view-only',
    keys: [{ chord: ['Mod+Shift+L'], vscodeCommandId: 'editor.action.selectHighlights' }],
    title: 'Select all occurrences',
    vscodeCommandIds: ['editor.action.selectHighlights'],
  }),
  defineEditorCommand({
    icon: SwapIcon,
    id: 'editor.action.changeAll',
    undoCategory: 'view-only',
    keys: [{ chord: ['Mod+F2'], vscodeCommandId: 'editor.action.changeAll' }],
    title: 'Change all occurrences',
    vscodeCommandIds: ['editor.action.changeAll'],
  }),
  // VS Code binds this to Mod+Shift+\, which the hotkey layer refuses: Shift with punctuation is
  // layout-dependent (see PunctuationKey). Mod+\ is unclaimed and keeps the backslash mnemonic.
  defineEditorCommand({
    id: 'editor.action.jumpToBracket',
    undoCategory: 'view-only',
    keys: [{ chord: ['Mod+\\'], vscodeCommandId: 'editor.action.jumpToBracket' }],
    title: 'Go to bracket',
    vscodeCommandIds: ['editor.action.jumpToBracket'],
  }),
  // VS Code's subword motion, which it ships on Ctrl+Alt+Arrow on macOS.
  defineEditorCommand({
    id: 'cursorWordPartLeft',
    undoCategory: 'view-only',
    keys: [
      {
        chord: ['Control+Alt+ArrowLeft'],
        platforms: ['mac'],
        vscodeCommandId: 'cursorWordPartLeft',
      },
    ],
    title: 'Cursor word part left',
    vscodeCommandIds: ['cursorWordPartLeft'],
  }),
  defineEditorCommand({
    id: 'cursorWordPartRight',
    undoCategory: 'view-only',
    keys: [
      {
        chord: ['Control+Alt+ArrowRight'],
        platforms: ['mac'],
        vscodeCommandId: 'cursorWordPartRight',
      },
    ],
    title: 'Cursor word part right',
    vscodeCommandIds: ['cursorWordPartRight'],
  }),
  defineEditorCommand({
    id: 'editor.action.trimTrailingWhitespace',
    undoCategory: 'text-edit',
    title: 'Trim trailing whitespace',
    vscodeCommandIds: ['editor.action.trimTrailingWhitespace'],
  }),
  defineEditorCommand({
    id: 'editor.action.sortLinesAscending',
    undoCategory: 'text-edit',
    title: 'Sort lines ascending',
    vscodeCommandIds: ['editor.action.sortLinesAscending'],
  }),
  defineEditorCommand({
    id: 'editor.action.sortLinesDescending',
    undoCategory: 'text-edit',
    title: 'Sort lines descending',
    vscodeCommandIds: ['editor.action.sortLinesDescending'],
  }),
  defineEditorCommand({
    id: 'editor.action.joinLines',
    undoCategory: 'text-edit',
    keys: [
      { chord: ['Control+J'], platforms: ['mac'], vscodeCommandId: 'editor.action.joinLines' },
    ],
    title: 'Join lines',
    vscodeCommandIds: ['editor.action.joinLines'],
  }),
  // Duplicate Selection stays palette-only, as in VS Code: Alt+Shift+Down is Copy Line Down, and
  // taking that key would replace a line command with a selection one.
  defineEditorCommand({
    id: 'editor.action.duplicateSelection',
    undoCategory: 'text-edit',
    title: 'Duplicate selection',
    vscodeCommandIds: ['editor.action.duplicateSelection'],
  }),
  defineEditorCommand({
    id: 'editor.action.transformToUppercase',
    undoCategory: 'text-edit',
    title: 'Transform to uppercase',
    vscodeCommandIds: ['editor.action.transformToUppercase'],
  }),
  defineEditorCommand({
    id: 'editor.action.transformToLowercase',
    undoCategory: 'text-edit',
    title: 'Transform to lowercase',
    vscodeCommandIds: ['editor.action.transformToLowercase'],
  }),
  defineEditorCommand({
    id: 'editor.action.transformToTitlecase',
    undoCategory: 'text-edit',
    title: 'Transform to title case',
    vscodeCommandIds: ['editor.action.transformToTitlecase'],
  }),
  defineEditorCommand({
    id: 'editor.action.rename',
    undoCategory: 'text-edit',
    keys: [{ chord: ['F2'], vscodeCommandId: 'editor.action.rename' }],
    title: 'Rename symbol',
    vscodeCommandIds: ['editor.action.rename'],
  }),
  // VS Code writes this Shift+Alt+F; the hotkey layer canonicalises modifiers as Alt+Shift.
  defineEditorCommand({
    id: 'editor.action.formatDocument',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Alt+Shift+F'], vscodeCommandId: 'editor.action.formatDocument' }],
    title: 'Format document',
    vscodeCommandIds: ['editor.action.formatDocument'],
  }),
  defineEditorCommand({
    id: 'editor.action.toggleWordWrap',
    undoCategory: 'view-only',
    keys: [{ chord: ['Alt+Z'], vscodeCommandId: 'editor.action.toggleWordWrap' }],
    title: 'Toggle word wrap',
    vscodeCommandIds: ['editor.action.toggleWordWrap'],
  }),
  defineEditorCommand({
    id: 'editor.action.moveSelectionToNextFindMatch',
    undoCategory: 'view-only',
    title: 'Move last selection to next find match',
    vscodeCommandIds: ['editor.action.moveSelectionToNextFindMatch'],
  }),
  defineEditorCommand({
    id: 'deleteBackward',
    undoCategory: 'text-edit',
    keys: [
      { chord: ['Backspace'] },
      { chord: ['Shift+Backspace'] },
      { chord: ['Control+H'], platforms: ['mac'] },
    ],
    title: 'Delete backward',
  }),
  defineEditorCommand({
    id: 'deleteForward',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Delete'] }, { chord: ['Control+D'], platforms: ['mac'] }],
    title: 'Delete forward',
  }),
  // TODO: Tab should not insert spaces at the cursor position; it should indent
  // at the beginning of the line. Make this behavior configurable — may want to
  // wait for the settings feature before wiring it up.
  defineEditorCommand({
    icon: TextIndentIcon,
    id: 'indentSelection',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Tab'], vscodeCommandId: 'tab' }],
    title: 'Indent selection',
    vscodeCommandIds: ['tab'],
  }),
  defineEditorCommand({
    icon: TextOutdentIcon,
    id: 'outdentSelection',
    undoCategory: 'text-edit',
    keys: [{ chord: ['Shift+Tab'], vscodeCommandId: 'outdent' }],
    title: 'Outdent selection',
    vscodeCommandIds: ['outdent'],
  }),
  defineEditorCommand({
    id: 'cursorLeft',
    undoCategory: 'view-only',
    keys: [
      { chord: ['ArrowLeft'], vscodeCommandId: 'cursorLeft' },
      { chord: ['Control+B'], platforms: ['mac'], vscodeCommandId: 'cursorLeft' },
    ],
    title: 'Move cursor left',
    vscodeCommandIds: ['cursorLeft'],
  }),
  defineEditorCommand({
    id: 'cursorRight',
    undoCategory: 'view-only',
    keys: [
      { chord: ['ArrowRight'], vscodeCommandId: 'cursorRight' },
      { chord: ['Control+F'], platforms: ['mac'], vscodeCommandId: 'cursorRight' },
    ],
    title: 'Move cursor right',
    vscodeCommandIds: ['cursorRight'],
  }),
  defineEditorCommand({
    id: 'cursorUp',
    undoCategory: 'view-only',
    keys: [
      { chord: ['ArrowUp'], vscodeCommandId: 'cursorUp' },
      { chord: ['Control+P'], platforms: ['mac'], vscodeCommandId: 'cursorUp' },
    ],
    title: 'Move cursor up',
    vscodeCommandIds: ['cursorUp'],
  }),
  defineEditorCommand({
    id: 'cursorDown',
    undoCategory: 'view-only',
    keys: [
      { chord: ['ArrowDown'], vscodeCommandId: 'cursorDown' },
      { chord: ['Control+N'], platforms: ['mac'], vscodeCommandId: 'cursorDown' },
    ],
    title: 'Move cursor down',
    vscodeCommandIds: ['cursorDown'],
  }),
  defineEditorCommand({
    id: 'selectLeft',
    undoCategory: 'view-only',
    keys: [{ chord: ['Shift+ArrowLeft'], vscodeCommandId: 'cursorLeftSelect' }],
    title: 'Select left',
    vscodeCommandIds: ['cursorLeftSelect'],
  }),
  defineEditorCommand({
    id: 'selectRight',
    undoCategory: 'view-only',
    keys: [{ chord: ['Shift+ArrowRight'], vscodeCommandId: 'cursorRightSelect' }],
    title: 'Select right',
    vscodeCommandIds: ['cursorRightSelect'],
  }),
  defineEditorCommand({
    id: 'selectUp',
    undoCategory: 'view-only',
    keys: [{ chord: ['Shift+ArrowUp'], vscodeCommandId: 'cursorUpSelect' }],
    title: 'Select up',
    vscodeCommandIds: ['cursorUpSelect'],
  }),
  defineEditorCommand({
    id: 'selectDown',
    undoCategory: 'view-only',
    keys: [{ chord: ['Shift+ArrowDown'], vscodeCommandId: 'cursorDownSelect' }],
    title: 'Select down',
    vscodeCommandIds: ['cursorDownSelect'],
  }),
  defineEditorCommand({
    id: 'cursorWordLeft',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Alt+ArrowLeft'], platforms: ['mac'], vscodeCommandId: 'cursorWordLeft' },
      {
        chord: ['Control+ArrowLeft'],
        platforms: ['windows', 'linux'],
        vscodeCommandId: 'cursorWordLeft',
      },
    ],
    title: 'Move cursor word left',
    vscodeCommandIds: ['cursorWordLeft'],
  }),
  defineEditorCommand({
    id: 'cursorWordRight',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Alt+ArrowRight'], platforms: ['mac'], vscodeCommandId: 'cursorWordEndRight' },
      {
        chord: ['Control+ArrowRight'],
        platforms: ['windows', 'linux'],
        vscodeCommandId: 'cursorWordEndRight',
      },
    ],
    title: 'Move cursor word right',
    vscodeCommandIds: ['cursorWordRight', 'cursorWordEndRight'],
  }),
  defineEditorCommand({
    id: 'selectWordLeft',
    undoCategory: 'view-only',
    keys: [
      {
        chord: ['Alt+Shift+ArrowLeft'],
        platforms: ['mac'],
        vscodeCommandId: 'cursorWordLeftSelect',
      },
      {
        chord: ['Control+Shift+ArrowLeft'],
        platforms: ['windows', 'linux'],
        vscodeCommandId: 'cursorWordLeftSelect',
      },
    ],
    title: 'Select word left',
    vscodeCommandIds: ['cursorWordLeftSelect'],
  }),
  defineEditorCommand({
    id: 'selectWordRight',
    undoCategory: 'view-only',
    keys: [
      {
        chord: ['Alt+Shift+ArrowRight'],
        platforms: ['mac'],
        vscodeCommandId: 'cursorWordEndRightSelect',
      },
      {
        chord: ['Control+Shift+ArrowRight'],
        platforms: ['windows', 'linux'],
        vscodeCommandId: 'cursorWordEndRightSelect',
      },
    ],
    title: 'Select word right',
    vscodeCommandIds: ['cursorWordRightSelect', 'cursorWordEndRightSelect'],
  }),
  defineEditorCommand({
    id: 'cursorLineStart',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Home'], vscodeCommandId: 'cursorHome' },
      { chord: ['Mod+ArrowLeft'], platforms: ['mac'], vscodeCommandId: 'cursorHome' },
      { chord: ['Control+A'], platforms: ['mac'], vscodeCommandId: 'cursorLineStart' },
    ],
    title: 'Move cursor to line start',
    vscodeCommandIds: ['cursorHome', 'cursorLineStart'],
  }),
  defineEditorCommand({
    id: 'cursorLineEnd',
    undoCategory: 'view-only',
    keys: [
      { chord: ['End'], vscodeCommandId: 'cursorEnd' },
      { chord: ['Mod+ArrowRight'], platforms: ['mac'], vscodeCommandId: 'cursorEnd' },
      { chord: ['Control+E'], platforms: ['mac'], vscodeCommandId: 'cursorLineEnd' },
    ],
    title: 'Move cursor to line end',
    vscodeCommandIds: ['cursorEnd', 'cursorLineEnd'],
  }),
  defineEditorCommand({
    id: 'selectLineStart',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Shift+Home'], vscodeCommandId: 'cursorHomeSelect' },
      { chord: ['Mod+Shift+ArrowLeft'], platforms: ['mac'], vscodeCommandId: 'cursorHomeSelect' },
      { chord: ['Control+Shift+A'], platforms: ['mac'], vscodeCommandId: 'cursorLineStartSelect' },
    ],
    title: 'Select to line start',
    vscodeCommandIds: ['cursorHomeSelect', 'cursorLineStartSelect'],
  }),
  defineEditorCommand({
    id: 'selectLineEnd',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Shift+End'], vscodeCommandId: 'cursorEndSelect' },
      { chord: ['Mod+Shift+ArrowRight'], platforms: ['mac'], vscodeCommandId: 'cursorEndSelect' },
      { chord: ['Control+Shift+E'], platforms: ['mac'], vscodeCommandId: 'cursorLineEndSelect' },
    ],
    title: 'Select to line end',
    vscodeCommandIds: ['cursorEndSelect', 'cursorLineEndSelect'],
  }),
  defineEditorCommand({
    id: 'cursorPageUp',
    undoCategory: 'view-only',
    keys: [{ chord: ['PageUp'], vscodeCommandId: 'cursorPageUp' }],
    title: 'Move cursor page up',
    vscodeCommandIds: ['cursorPageUp'],
  }),
  defineEditorCommand({
    id: 'cursorPageDown',
    undoCategory: 'view-only',
    keys: [{ chord: ['PageDown'], vscodeCommandId: 'cursorPageDown' }],
    title: 'Move cursor page down',
    vscodeCommandIds: ['cursorPageDown'],
  }),
  defineEditorCommand({
    id: 'selectPageUp',
    undoCategory: 'view-only',
    keys: [{ chord: ['Shift+PageUp'], vscodeCommandId: 'cursorPageUpSelect' }],
    title: 'Select page up',
    vscodeCommandIds: ['cursorPageUpSelect'],
  }),
  defineEditorCommand({
    id: 'selectPageDown',
    undoCategory: 'view-only',
    keys: [{ chord: ['Shift+PageDown'], vscodeCommandId: 'cursorPageDownSelect' }],
    title: 'Select page down',
    vscodeCommandIds: ['cursorPageDownSelect'],
  }),
  defineEditorCommand({
    id: 'cursorDocumentStart',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Mod+ArrowUp'], platforms: ['mac'], vscodeCommandId: 'cursorTop' },
      { chord: ['Control+Home'], platforms: ['windows', 'linux'], vscodeCommandId: 'cursorTop' },
    ],
    title: 'Move cursor to document start',
    vscodeCommandIds: ['cursorTop'],
  }),
  defineEditorCommand({
    id: 'cursorDocumentEnd',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Mod+ArrowDown'], platforms: ['mac'], vscodeCommandId: 'cursorBottom' },
      { chord: ['Control+End'], platforms: ['windows', 'linux'], vscodeCommandId: 'cursorBottom' },
    ],
    title: 'Move cursor to document end',
    vscodeCommandIds: ['cursorBottom'],
  }),
  defineEditorCommand({
    id: 'selectDocumentStart',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Mod+Shift+ArrowUp'], platforms: ['mac'], vscodeCommandId: 'cursorTopSelect' },
      {
        chord: ['Control+Shift+Home'],
        platforms: ['windows', 'linux'],
        vscodeCommandId: 'cursorTopSelect',
      },
    ],
    title: 'Select to document start',
    vscodeCommandIds: ['cursorTopSelect'],
  }),
  defineEditorCommand({
    id: 'selectDocumentEnd',
    undoCategory: 'view-only',
    keys: [
      { chord: ['Mod+Shift+ArrowDown'], platforms: ['mac'], vscodeCommandId: 'cursorBottomSelect' },
      {
        chord: ['Control+Shift+End'],
        platforms: ['windows', 'linux'],
        vscodeCommandId: 'cursorBottomSelect',
      },
    ],
    title: 'Select to document end',
    vscodeCommandIds: ['cursorBottomSelect'],
  }),
]
