import { editorCommandMetadata } from '@workspace/client-core/commands/editor'
import {
  ArrowArcLeftIcon,
  ArrowArcRightIcon,
  ArrowLineDownIcon,
  ArrowLineUpIcon,
  ArrowSquareOutIcon,
  ArrowsOutLineVerticalIcon,
  ChatTextIcon,
  CopySimpleIcon,
  CursorClickIcon,
  LinkIcon,
  MagnifyingGlassIcon,
  SelectionIcon,
  SwapIcon,
  TextIndentIcon,
  TextOutdentIcon,
  TrashIcon,
} from '@phosphor-icons/react'

export const editorCommands = [
  { ...editorCommandMetadata['undo'], icon: ArrowArcLeftIcon },
  { ...editorCommandMetadata['redo'], icon: ArrowArcRightIcon },
  { ...editorCommandMetadata['find'], icon: MagnifyingGlassIcon },
  { ...editorCommandMetadata['findReplace'], icon: SwapIcon },
  { ...editorCommandMetadata['findNext'], icon: MagnifyingGlassIcon },
  { ...editorCommandMetadata['findPrevious'], icon: MagnifyingGlassIcon },
  { ...editorCommandMetadata['goToDefinition'], icon: ArrowSquareOutIcon },
  { ...editorCommandMetadata['editor.action.goToImplementation'] },
  { ...editorCommandMetadata['editor.action.goToTypeDefinition'] },
  { ...editorCommandMetadata['editor.action.peekDefinition'] },
  { ...editorCommandMetadata['editor.action.revealDefinitionAside'] },
  { ...editorCommandMetadata['editor.action.showHover'], icon: ChatTextIcon },
  { ...editorCommandMetadata['editor.action.goToReferences'], icon: LinkIcon },
  { ...editorCommandMetadata['closeFind'] },
  { ...editorCommandMetadata['toggleFindCaseSensitive'] },
  { ...editorCommandMetadata['toggleFindWholeWord'] },
  { ...editorCommandMetadata['toggleFindRegex'] },
  { ...editorCommandMetadata['toggleFindInSelection'] },
  { ...editorCommandMetadata['togglePreserveCase'] },
  { ...editorCommandMetadata['replaceOne'], icon: SwapIcon },
  { ...editorCommandMetadata['replaceAll'], icon: SwapIcon },
  { ...editorCommandMetadata['selectAllMatches'], icon: SelectionIcon },
  { ...editorCommandMetadata['selectAll'], icon: SelectionIcon },
  { ...editorCommandMetadata['addNextOccurrence'], icon: CursorClickIcon },
  { ...editorCommandMetadata['clearSecondarySelections'], icon: CursorClickIcon },
  { ...editorCommandMetadata['deleteWordLeft'] },
  { ...editorCommandMetadata['deleteWordRight'] },
  { ...editorCommandMetadata['editor.action.deleteLines'], icon: TrashIcon },
  { ...editorCommandMetadata['editor.action.copyLinesUpAction'], icon: CopySimpleIcon },
  { ...editorCommandMetadata['editor.action.copyLinesDownAction'], icon: CopySimpleIcon },
  { ...editorCommandMetadata['editor.action.moveLinesUpAction'], icon: ArrowsOutLineVerticalIcon },
  {
    ...editorCommandMetadata['editor.action.moveLinesDownAction'],
    icon: ArrowsOutLineVerticalIcon,
  },
  { ...editorCommandMetadata['editor.action.insertLineBefore'], icon: ArrowLineUpIcon },
  { ...editorCommandMetadata['editor.action.insertLineAfter'], icon: ArrowLineDownIcon },
  { ...editorCommandMetadata['editor.action.commentLine'], icon: ChatTextIcon },
  { ...editorCommandMetadata['editor.action.blockComment'], icon: ChatTextIcon },
  { ...editorCommandMetadata['editor.action.indentLines'], icon: TextIndentIcon },
  { ...editorCommandMetadata['editor.action.outdentLines'], icon: TextOutdentIcon },
  { ...editorCommandMetadata['editor.action.insertCursorAbove'], icon: CursorClickIcon },
  { ...editorCommandMetadata['editor.action.insertCursorBelow'], icon: CursorClickIcon },
  { ...editorCommandMetadata['editor.action.selectHighlights'], icon: SelectionIcon },
  { ...editorCommandMetadata['editor.action.changeAll'], icon: SwapIcon },
  { ...editorCommandMetadata['editor.action.jumpToBracket'] },
  { ...editorCommandMetadata['cursorWordPartLeft'] },
  { ...editorCommandMetadata['cursorWordPartRight'] },
  { ...editorCommandMetadata['editor.action.trimTrailingWhitespace'] },
  { ...editorCommandMetadata['editor.action.sortLinesAscending'] },
  { ...editorCommandMetadata['editor.action.sortLinesDescending'] },
  { ...editorCommandMetadata['editor.action.joinLines'] },
  { ...editorCommandMetadata['editor.action.duplicateSelection'] },
  { ...editorCommandMetadata['editor.action.transformToUppercase'] },
  { ...editorCommandMetadata['editor.action.transformToLowercase'] },
  { ...editorCommandMetadata['editor.action.transformToTitlecase'] },
  { ...editorCommandMetadata['editor.action.rename'] },
  { ...editorCommandMetadata['editor.action.formatDocument'] },
  { ...editorCommandMetadata['editor.action.toggleWordWrap'] },
  { ...editorCommandMetadata['editor.action.moveSelectionToNextFindMatch'] },
  { ...editorCommandMetadata['deleteBackward'] },
  { ...editorCommandMetadata['deleteForward'] },
  { ...editorCommandMetadata['indentSelection'], icon: TextIndentIcon },
  { ...editorCommandMetadata['outdentSelection'], icon: TextOutdentIcon },
  { ...editorCommandMetadata['cursorLeft'] },
  { ...editorCommandMetadata['cursorRight'] },
  { ...editorCommandMetadata['cursorUp'] },
  { ...editorCommandMetadata['cursorDown'] },
  { ...editorCommandMetadata['selectLeft'] },
  { ...editorCommandMetadata['selectRight'] },
  { ...editorCommandMetadata['selectUp'] },
  { ...editorCommandMetadata['selectDown'] },
  { ...editorCommandMetadata['cursorWordLeft'] },
  { ...editorCommandMetadata['cursorWordRight'] },
  { ...editorCommandMetadata['selectWordLeft'] },
  { ...editorCommandMetadata['selectWordRight'] },
  { ...editorCommandMetadata['cursorLineStart'] },
  { ...editorCommandMetadata['cursorLineEnd'] },
  { ...editorCommandMetadata['selectLineStart'] },
  { ...editorCommandMetadata['selectLineEnd'] },
  { ...editorCommandMetadata['cursorPageUp'] },
  { ...editorCommandMetadata['cursorPageDown'] },
  { ...editorCommandMetadata['selectPageUp'] },
  { ...editorCommandMetadata['selectPageDown'] },
  { ...editorCommandMetadata['cursorDocumentStart'] },
  { ...editorCommandMetadata['cursorDocumentEnd'] },
  { ...editorCommandMetadata['selectDocumentStart'] },
  { ...editorCommandMetadata['selectDocumentEnd'] },

  { ...editorCommandMetadata['cursorUndo'] },
  { ...editorCommandMetadata['cursorRedo'] },
  { ...editorCommandMetadata['editor.action.goToDefinition'] },
  { ...editorCommandMetadata['editor.action.marker.next'] },
  { ...editorCommandMetadata['editor.action.marker.prev'] },
  { ...editorCommandMetadata['editor.action.smartSelect.expand'] },
  { ...editorCommandMetadata['editor.action.smartSelect.shrink'] },
  { ...editorCommandMetadata['editor.action.toggleTabFocusMode'] },
  { ...editorCommandMetadata['editor.action.autoFix'] },
  { ...editorCommandMetadata['editor.action.inlineSuggest.commit'] },
  { ...editorCommandMetadata['editor.action.inlineSuggest.acceptNextWord'] },
  { ...editorCommandMetadata['editor.fold'] },
  { ...editorCommandMetadata['editor.unfold'] },
  { ...editorCommandMetadata['editor.foldRecursively'] },
  { ...editorCommandMetadata['editor.unfoldRecursively'] },
  { ...editorCommandMetadata['editor.foldAll'] },
  { ...editorCommandMetadata['editor.unfoldAll'] },
  { ...editorCommandMetadata['editor.createFoldingRangeFromSelection'] },
  { ...editorCommandMetadata['editor.removeManualFoldingRanges'] },
  { ...editorCommandMetadata['deleteWordPartLeft'] },
  { ...editorCommandMetadata['deleteWordPartRight'] },
  { ...editorCommandMetadata['editor.action.reindentlines'] },
  { ...editorCommandMetadata['editor.action.reindentselectedlines'] },
  { ...editorCommandMetadata['cursorWordPartLeftSelect'] },
  { ...editorCommandMetadata['cursorWordPartRightSelect'] },
  { ...editorCommandMetadata['cursorColumnSelectLeft'] },
  { ...editorCommandMetadata['cursorColumnSelectRight'] },
  { ...editorCommandMetadata['cursorColumnSelectUp'] },
  { ...editorCommandMetadata['cursorColumnSelectDown'] },
  { ...editorCommandMetadata['cursorColumnSelectPageUp'] },
  { ...editorCommandMetadata['cursorColumnSelectPageDown'] },
  { ...editorCommandMetadata['editor.foldLevel1'] },
  { ...editorCommandMetadata['editor.foldLevel2'] },
  { ...editorCommandMetadata['editor.foldLevel3'] },
  { ...editorCommandMetadata['editor.foldLevel4'] },
  { ...editorCommandMetadata['editor.foldLevel5'] },
  { ...editorCommandMetadata['editor.foldLevel6'] },
  { ...editorCommandMetadata['editor.foldLevel7'] },
]
