import { expect, test } from '../../../../../test/fixtures'
import { languageIdForFilePath } from '@/features/editor/utils/file-path'

test('keeps the tree-sitter-backed language ids stable', () => {
  expect(languageIdForFilePath('/repo/src/app.ts')).toBe('typescript')
  expect(languageIdForFilePath('/repo/src/app.tsx')).toBe('typescript')
  expect(languageIdForFilePath('/repo/src/app.js')).toBe('javascript')
  expect(languageIdForFilePath('/repo/src/app.jsx')).toBe('javascript')
  expect(languageIdForFilePath('/repo/src/app.css')).toBe('css')
  expect(languageIdForFilePath('/repo/src/app.html')).toBe('html')
  expect(languageIdForFilePath('/repo/package.json')).toBe('json')
  expect(languageIdForFilePath('/repo/README.md')).toBe('markdown')
})

test('maps common extensions to their shiki language ids', () => {
  expect(languageIdForFilePath('/repo/main.py')).toBe('python')
  expect(languageIdForFilePath('/repo/main.rs')).toBe('rust')
  expect(languageIdForFilePath('/repo/main.go')).toBe('go')
  expect(languageIdForFilePath('/repo/Main.java')).toBe('java')
  expect(languageIdForFilePath('/repo/main.kt')).toBe('kotlin')
  expect(languageIdForFilePath('/repo/main.scala')).toBe('scala')
  expect(languageIdForFilePath('/repo/main.c')).toBe('c')
  expect(languageIdForFilePath('/repo/main.cpp')).toBe('cpp')
  expect(languageIdForFilePath('/repo/main.h')).toBe('c')
  expect(languageIdForFilePath('/repo/main.hpp')).toBe('cpp')
  expect(languageIdForFilePath('/repo/main.cs')).toBe('csharp')
  expect(languageIdForFilePath('/repo/main.rb')).toBe('ruby')
  expect(languageIdForFilePath('/repo/index.php')).toBe('php')
  expect(languageIdForFilePath('/repo/main.swift')).toBe('swift')
  expect(languageIdForFilePath('/repo/app.yml')).toBe('yaml')
  expect(languageIdForFilePath('/repo/app.yaml')).toBe('yaml')
  expect(languageIdForFilePath('/repo/Cargo.toml')).toBe('toml')
  expect(languageIdForFilePath('/repo/index.xml')).toBe('xml')
  expect(languageIdForFilePath('/repo/query.sql')).toBe('sql')
  expect(languageIdForFilePath('/repo/run.sh')).toBe('shellscript')
  expect(languageIdForFilePath('/repo/run.bash')).toBe('shellscript')
  expect(languageIdForFilePath('/repo/run.zsh')).toBe('shellscript')
  expect(languageIdForFilePath('/repo/main.lua')).toBe('lua')
  expect(languageIdForFilePath('/repo/main.r')).toBe('r')
  expect(languageIdForFilePath('/repo/main.dart')).toBe('dart')
  expect(languageIdForFilePath('/repo/main.ex')).toBe('elixir')
  expect(languageIdForFilePath('/repo/main.exs')).toBe('elixir')
  expect(languageIdForFilePath('/repo/schema.graphql')).toBe('graphql')
  expect(languageIdForFilePath('/repo/App.vue')).toBe('vue')
  expect(languageIdForFilePath('/repo/App.svelte')).toBe('svelte')
  expect(languageIdForFilePath('/repo/change.diff')).toBe('diff')
  expect(languageIdForFilePath('/repo/change.patch')).toBe('diff')
  expect(languageIdForFilePath('/repo/app.ini')).toBe('ini')
  expect(languageIdForFilePath('/repo/deploy.ps1')).toBe('powershell')
  expect(languageIdForFilePath('/repo/main.tf')).toBe('terraform')
})

test('maps extensionless dockerfile and makefile basenames', () => {
  expect(languageIdForFilePath('/repo/Dockerfile')).toBe('dockerfile')
  expect(languageIdForFilePath('/repo/Makefile')).toBe('makefile')
  expect(languageIdForFilePath('/repo/extra.mk')).toBe('makefile')
})

test('returns null for unknown ids so they never reach shiki', () => {
  expect(languageIdForFilePath('/repo/notes.txt')).toBeNull()
  expect(languageIdForFilePath('/repo/README')).toBeNull()
})
